function dispatch(cid,pid){const c=state.contracts.find(x=>x.id===cid),p=state.parties.find(x=>x.id===pid);if(!c||!p)return;let members=p.members.map(id=>state.roster.find(r=>r.id===id)).filter(Boolean);if(!members.length)return;members.forEach(r=>r.status='Expedition');p.expedition={contract:c,progress:0,step:0,events:[`Departed Greyhaven with ${members.length} adventurer(s).`],battle:null};state.contracts=state.contracts.filter(x=>x.id!==cid);state.log.push(`${p.name} accepted “${c.title}”.`);closeModal();state.tab='contracts';toast(`${p.name} departed.`);render()}
const phaseEvents=['A cold rain begins. The road turns to mud.','Fresh tracks cross the route. Nobody agrees what made them.','A ruined shrine offers a dry place to rest.','Someone sees movement beyond the torchlight.','The party finds old blood but no body.','A merchant wagon passes the other way and refuses to stop.','Crows follow the party for nearly a mile.'];
function advanceExpedition(pid,manual=false){const p=state.parties.find(x=>x.id===pid);if(!p||!p.expedition)return;const e=p.expedition;if(e.battle){combatRound(p);return}e.step++;e.progress=clamp(e.progress+rnd(13,23),0,100);if(e.progress<65){e.events.push(`+${e.progress}% — ${pick(phaseEvents)}`)}else if(!e.fought){e.fought=true;startCombat(p);return}else e.events.push(`+${e.progress}% — The party pushes toward the objective.`);if(e.progress>=100&&!e.battle)finishExpedition(p);render()}
function startCombat(p){const e=p.expedition,c=e.contract;let members=p.members.map(id=>state.roster.find(r=>r.id===id)).filter(Boolean);let pp=Math.max(20,totalPower(p)),ep=c.risk*55+rnd(-10,25)+c.unknown*8;e.battle={partyName:p.name,partyHp:100,enemyHp:100,partyPower:pp,enemyPower:ep,enemy:pick(c.enemies),round:0};e.events.push(`ENCOUNTER — ${c.enemies.join(', ')}.`);e.events.push('Weapons out. Combat begins.');render();setTimeout(()=>combatRound(p),350)}
function combatRound(p){const b=p.expedition?.battle;if(!b)return;b.round++;let pd=rnd(10,19)*(b.partyPower/(b.enemyPower+30)),ed=rnd(7,17)*(b.enemyPower/(b.partyPower+30));if(Math.random()<.12)pd*=1.7;if(Math.random()<.12)ed*=1.6;b.enemyHp=clamp(b.enemyHp-pd,0,100);b.partyHp=clamp(b.partyHp-ed,0,100);p.expedition.events.push(`Round ${b.round}: party deals ${Math.round(pd)}%, takes ${Math.round(ed)}%.`);if(b.enemyHp<=0||b.partyHp<=0||b.round>=8){resolveCombat(p,b.partyHp>b.enemyHp)}render()}
function resolveCombat(p,win){let e=p.expedition,members=p.members.map(id=>state.roster.find(r=>r.id===id)).filter(Boolean);let b=e.battle;e.battle=null;if(win){e.events.push('The enemy line breaks. Survivors finish the fight.');members.forEach(r=>r.kills+=rnd(0,2));e.progress=Math.max(e.progress,78)}else{e.events.push('The party is forced into a bloody retreat.');e.failed=true;e.progress=100}let severity=win?clamp(100-b.partyHp,5,75):rnd(55,95);members.forEach(r=>{if(Math.random()<severity/140){let dmg=rnd(12,35)+Math.floor(severity/5);r.hp=clamp(r.hp-dmg,1,r.maxHp);if(r.hp<45||Math.random()<.15){r.injury=pick(['Broken Ribs','Deep Cut','Crushed Hand','Concussion','Fevered Bite','Torn Shoulder']);r.recovery=rnd(2,5)+Math.max(0,2-(state.hq.Infirmary||0));r.status='Recovering';if(Math.random()<.18&&severity>60){r.scars.push(pick(['Split Brow','Missing Fingertip','Burn Scar','Bad Limp']))}}}});if(e.progress>=100)finishExpedition(p)}
function finishExpedition(p){const e=p.expedition,c=e.contract;let members=p.members.map(id=>state.roster.find(r=>r.id===id)).filter(Boolean);let success=!e.failed;let deaths=[];if(!success){members.forEach(r=>{let deathChance=.08*c.risk*Math.max(.3,1-(state.hq.Infirmary||0)*.12);if(Math.random()<deathChance){deaths.push(r);r.status='Dead';r.hp=0}})}else{members.forEach(r=>{if(r.status==='Expedition')r.status=r.injury?'Recovering':'Ready'})}
 members.forEach(r=>{r.missions++;if(r.status!=='Dead'){r.xp+=success?15+c.risk*10:8;levelCheck(r)}});
 if(success){let pay=Math.floor(c.reward*(1+(state.hq['Contract Office']||0)*.05));state.silver+=pay;state.renown+=c.risk*2;state.completed++;let loot=pick([...weaponLoot,...armorLoot,...miscLoot]);state.inventory.push({name:loot,type:weaponLoot.includes(loot)?'Weapon':armorLoot.includes(loot)?'Armor':'Material',qty:1});if(c.cache)state.caches.push({name:c.risk>=3?'Sealed Reliquary':'Battered Cache',from:c.title,risk:c.risk});if((c.risk>=3&&Math.random()<.10+.05*(state.hq['Occult Archive']||0))&&state.artifacts.length<(state.hq['Artifact Vault']?99:2)){let a=artifactPool.find(a=>!state.artifacts.some(x=>x.name===a.name));if(a){state.artifacts.push(a);state.log.push(`ARTIFACT RECOVERED — ${a.name}.`)}}state.log.push(`${p.name} completed “${c.title}” for ${pay}s. Loot: ${loot}.`);regionEffect(c.place,-rnd(4,9));state.lastReport={success:true,title:c.title,pay,loot,deaths:deaths.map(x=>x.name)} }else{state.renown=Math.max(0,state.renown-1);state.log.push(`${p.name} failed “${c.title}”. ${deaths.length?deaths.map(x=>x.name).join(', ')+' died.':'They returned in pieces, but alive.'}`);regionEffect(c.place,rnd(5,11));state.lastReport={success:false,title:c.title,pay:0,loot:null,deaths:deaths.map(x=>x.name)}}
 deaths.forEach(d=>{state.parties.forEach(q=>q.members=q.members.filter(id=>id!==d.id))});
 p.expedition=null;advanceDay();showReport();render()}
function showReport(){let r=state.lastReport;if(!r)return;modal(`<div class="sheetHead"><h3>${r.success?'CONTRACT COMPLETE':'CONTRACT FAILED'}</h3><button class="x" onclick="closeModal()">✕</button></div><div class="hero"><div class="kicker">${r.title}</div><h2>${r.success?'They came back.':'Greyhaven gets quieter.'}</h2><p>${r.success?`Payment ${r.pay}s. Recovered ${r.loot}.`:'The company gains no reward.'}</p></div>${r.deaths.length?`<div class="card danger"><b>Dead:</b> ${r.deaths.join(', ')}</div>`:'<div class="card good">No confirmed deaths.</div>'}`)}
function levelCheck(r){while(r.xp>=r.xpNext){r.xp-=r.xpNext;r.lvl++;r.xpNext=Math.floor(r.xpNext*1.35);let keys=Object.keys(r.stats);r.stats[pick(keys)]+=rnd(2,4);r.maxHp+=5;r.hp=Math.min(r.maxHp,r.hp+10);state.log.push(`${r.name} reached Level ${r.lvl}.`)}}
function advanceDay(){state.day++;Object.keys(state.threats).forEach(k=>state.threats[k]=clamp(state.threats[k]+rnd(1,4),0,100));if(state.day%7===0){let wages=state.roster.filter(r=>r.status!=='Dead').reduce((s,r)=>s+r.wage,0);state.silver-=wages;state.log.push(`Weekly wages paid: ${wages}s.`);if(state.silver<0){state.renown=Math.max(0,state.renown-2);state.log.push('The treasury is empty. People are talking.')}}let count=5+(state.hq['Contract Office']||0);while(state.contracts.length<count)state.contracts.push(contractGen());state.contracts=state.contracts.filter(c=>c.expires>=state.day);state.recruits=Array.from({length:6+(state.renown>15?2:0)},recruitGen);if(state.hq['Training Yard'])state.roster.filter(r=>r.status==='Ready').forEach(r=>{r.xp+=2*state.hq['Training Yard'];levelCheck(r)})}
function tickRecoveries(){if(!state._lastRecoveryDay)state._lastRecoveryDay=state.day;if(state._lastRecoveryDay!==state.day){let d=state.day-state._lastRecoveryDay;state.roster.forEach(r=>{if(r.recovery>0){r.recovery=Math.max(0,r.recovery-d);r.hp=Math.min(r.maxHp,r.hp+d*(10+state.hq.Infirmary*4));if(r.recovery===0&&r.status==='Recovering'){r.status='Ready';r.injury=null}}});state._lastRecoveryDay=state.day}}
function regionEffect(place,n){if(state.threats[place]!=null)state.threats[place]=clamp(state.threats[place]+n,0,100)}
function upgrade(k){let lv=state.hq[k]||0,c=Math.floor(hqDefs[k].base*(1+lv*.75));if(state.silver<c)return;state.silver-=c;state.hq[k]=lv+1;state.log.push(`${k} upgraded to Level ${lv+1}.`);toast(`${k} upgraded.`);render()}
function infoHQ(k){let lv=state.hq[k]||0;modal(`<div class="sheetHead"><h3>${hqDefs[k].icon} ${k}</h3><button class="x" onclick="closeModal()">✕</button></div><p>${hqDefs[k].desc}</p><div class="card small">Current level: ${lv}<br>${k==='Barracks'?`Roster capacity: ${cap()}`:k==='Infirmary'?`Recovery bonus: ${lv*4} HP/day`:k==='Contract Office'?`Extra contract slots: ${lv}`:k==='Occult Archive'?`Unknown factors revealed: ${lv}`:'Higher levels improve this facility’s effect.'}</div>`)}
function openCache(i){let c=state.caches[i];if(!c)return;const cacheCard=document.querySelector(`[data-cache="${i}"]`)?.closest('.cache');if(cacheCard)cacheCard.classList.add('opening');setTimeout(()=>{let rolls=1+(c.risk>=3?1:0),found=[];for(let n=0;n<rolls;n++){let item=pick([...weaponLoot,...armorLoot,...miscLoot]);found.push(item);state.inventory.push({name:item,type:weaponLoot.includes(item)?'Weapon':armorLoot.includes(item)?'Armor':'Material',qty:1})}let silver=rnd(4,14)*c.risk;state.silver+=silver;let artifact=null;if(c.risk>=3&&Math.random()<.12+.04*(state.hq['Occult Archive']||0)){artifact=artifactPool.find(a=>!state.artifacts.some(x=>x.name===a.name));if(artifact&&state.artifacts.length<(state.hq['Artifact Vault']?99:2)){state.artifacts.push(artifact);found.push(artifact.name)}}state.caches.splice(i,1);modal(`<div class="cache lootburst"><div class="chest">💥</div><h3>${c.name} opened</h3><p class="gold"><b>+${silver}s</b></p>${found.map(x=>`<div class="card" style="margin:6px">${x}</div>`).join('')}</div><div class="actions"><button class="btn goldbtn" onclick="closeModal();render()">Take Loot</button></div>`);save()},260)}
window.render=render;
function showTutorial(){state.tutorial=false;save();modal(`<div class="sheetHead"><h3>THE BROKEN LANTERN COMPANY</h3><button class="x" onclick="closeModal()">✕</button></div><p class="small">You own a rotting coaching house in a province being eaten alive.</p><div class="card"><b>1. Hire somebody.</b><div class="small muted">Open Roster and hire one or two cheap recruits.</div></div><div class="card" style="margin-top:6px"><b>2. Build the Ash Dogs.</b><div class="small muted">Assign those recruits to your starting party.</div></div><div class="card" style="margin-top:6px"><b>3. Take a contract.</b><div class="small muted">Start with Risk 1. Push the expedition to move it forward and watch combat resolve.</div></div><div class="card" style="margin-top:6px"><b>4. Spend what survives.</b><div class="small muted">Gold, loot, injuries, levels, HQ upgrades, caches, and regional threats persist automatically.</div></div><div class="actions"><button class="btn primary" onclick="closeModal()">Open the doors</button></div>`)}
setInterval(()=>{let p=state.parties.find(p=>p.expedition);if(p&&document.visibilityState==='visible'){advanceExpedition(p.id,false)}},state.settings.fast?900:1700);
render();
