function render(){tickRecoveries();const app=document.getElementById('app');app.innerHTML=top()+`<div class="screen active">${state.tab==='hq'?renderHQ():state.tab==='roster'?renderRoster():state.tab==='contracts'?renderContracts():state.tab==='world'?renderWorld():renderVault()}</div>`;nav();wire();save();if(state.tutorial)setTimeout(showTutorial,80)}
function renderHQ(){const active=state.parties.filter(p=>p.expedition);return `<div class="hero"><div class="kicker">GREYHAVEN • THE GRAVEN MARCH</div><h2>Your company is nobody.</h2><p>Greyhaven can barely feed itself. Roads vanish under raiders and things worse than raiders. That makes desperate work plentiful.</p></div>
<div class="sectionTitle"><h3>Headquarters</h3><span>Abandoned coaching house</span></div><div class="grid2">${Object.entries(hqDefs).map(([k,d])=>{let lv=state.hq[k]||0,cost=Math.floor(d.base*(1+lv*.75));return `<div class="card hqtile"><div class="hqicon">${d.icon}</div><h4>${k} <span class="gold">Lv.${lv}</span></h4><div class="small muted">${d.desc}</div><div class="actions"><button class="btn ghost info" data-info="${k}">ⓘ</button><button class="btn ${state.silver>=cost?'goldbtn':''} upgrade" data-up="${k}" ${state.silver<cost?'disabled':''}>Upgrade ${cost}s</button></div></div>`}).join('')}</div>
<div class="sectionTitle"><h3>Active Expeditions</h3><span>${active.length}</span></div>${active.length?active.map(expeditionCard).join(''):'<div class="empty">No parties are in the field. Hire somebody, form a party, and take a contract.</div>'}
<div class="sectionTitle"><h3>Company Ledger</h3><button class="btn ghost" id="reset">Reset Save</button></div><div class="log">${state.log.slice(-12).reverse().map(x=>`<div>${x}</div>`).join('')}</div>`}
function expeditionCard(p){const e=p.expedition;return `<div class="card"><div class="statline"><b>${p.name}</b><span class="gold">${e.contract.title}</span></div><div class="bar goldbar"><i style="width:${e.progress}%"></i></div><div class="statline"><span>${e.progress}% complete</span><span>${e.contract.place}</span></div>${e.battle?renderBattle(e.battle):''}<div class="log">${e.events.slice(-7).map(x=>`<div>${x}</div>`).join('')}</div><div class="actions"><button class="btn primary advance" data-party="${p.id}">Push Expedition</button></div></div>`}
function renderBattle(b){return `<div class="combatrow"><div class="combatSide"><b>${b.partyName}</b><div class="hpbar"><i style="width:${b.partyHp}%"></i></div><div class="tiny muted">Company ${Math.round(b.partyHp)}%</div></div><div class="vs">VS</div><div class="combatSide"><b>${b.enemy}</b><div class="hpbar"><i style="width:${b.enemyHp}%"></i></div><div class="tiny muted">Enemy ${Math.round(b.enemyHp)}%</div></div></div>`}
function renderRoster(){return `<div class="hero"><div class="kicker">COMPANY ROSTER</div><h2>${employedCount()} employed</h2><p>Names become veterans, cripples, corpses, or legends. Most become one of the first three.</p></div>
<div class="sectionTitle"><h3>Your People</h3><span>Capacity ${cap()}</span></div><div class="list">${state.roster.length?state.roster.map(r=>rosterCard(r)).join(''):'<div class="empty">Nobody works for you yet.</div>'}</div>
<div class="sectionTitle"><h3>Tavern & Yard</h3><button class="btn ghost" id="refreshRecruits">Refresh 4s</button></div><div class="list">${state.recruits.map(recruitCard).join('')}</div>
<div class="sectionTitle"><h3>Parties</h3><span>Tap members to assign</span></div>${state.parties.map(p=>partyCard(p)).join('')}`}
function rosterCard(r){return `<div class="card member clickable inspect" data-id="${r.id}"><div class="portrait">${RACES[r.race]}</div><div><div class="statline"><h4>${r.name}</h4><span>Lv.${r.lvl}</span></div><div class="small muted">${r.race} • ${r.bg} • ${r.status}</div><div class="hpbar"><i style="width:${r.hp/r.maxHp*100}%"></i></div><div class="tags">${r.traits.map(t=>`<span class="tag">${t}</span>`).join('')}${r.injury?`<span class="tag danger">${r.injury}</span>`:''}</div></div></div>`}
function recruitCard(r){return `<div class="card recruit"><div class="portrait">${RACES[r.race]}</div><div><h4>${r.name}</h4><div class="small muted">${r.race} ${r.bg} • ${r.wage}s/week</div><div class="tags">${r.traits.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><button class="btn goldbtn hire" data-id="${r.id}" ${employedCount()>=cap()||state.silver<r.hire?'disabled':''}>Hire<br>${r.hire}s</button></div>`}
function partyCard(p){let members=p.members.map(id=>state.roster.find(r=>r.id===id)).filter(Boolean);return `<div class="card" style="margin-bottom:8px"><div class="statline"><b>${p.name}</b><span>${members.length}/4</span></div><div class="partyMembers">${members.map(r=>`<div class="facechip" title="${r.name}">${RACES[r.race]}<span class="lvl">${r.lvl}</span></div>`).join('')||'<span class="small muted">Empty party</span>'}</div><div class="actions"><button class="btn partyEdit" data-party="${p.id}" ${p.expedition?'disabled':''}>Assign Members</button></div></div>`}
function renderContracts(){let idle=state.parties.filter(p=>!p.expedition);return `<div class="hero"><div class="kicker">CONTRACT DESK</div><h2>Someone always needs killing.</h2><p>Risk ratings are estimates. Employers lie, survivors exaggerate, and the dead submit poor paperwork.</p></div>
<div class="sectionTitle"><h3>Available Contracts</h3><span>${state.contracts.length} notices</span></div><div class="list">${state.contracts.map(c=>contractCard(c,idle)).join('')}</div>
<div class="sectionTitle"><h3>Parties in the Field</h3><span>${state.parties.filter(p=>p.expedition).length}</span></div>${state.parties.filter(p=>p.expedition).map(expeditionCard).join('')||'<div class="empty">No active expeditions.</div>'}`}
function contractCard(c,idle){return `<div class="card contract risk${c.risk}"><div class="statline"><h4>${c.title}</h4><span class="risk">${'●'.repeat(c.risk)}<span class="off">${'○'.repeat(4-c.risk)}</span></span></div><p>${c.desc}</p><div class="grid2"><div class="small"><span class="muted">Location</span><br>${c.place}</div><div class="small"><span class="muted">Reward</span><br><b class="gold">${c.reward}s</b>${c.cache?' + cache':''}</div><div class="small"><span class="muted">Distance</span><br>${c.distance} miles</div><div class="small"><span class="muted">Unknowns</span><br>${Math.max(0,c.unknown-(state.hq['Occult Archive']||0))}</div></div><div class="actions"><button class="btn contractInfo" data-contract="${c.id}">Inspect</button><button class="btn primary take" data-contract="${c.id}" ${idle.length===0?'disabled':''}>Send Party</button></div></div>`}
function renderWorld(){const pos={'Greyhaven':[50,50],'Blackpine Forest':[24,22],'Drowned Farms':[73,28],'Redfang Hills':[20,77],'Saint Orrin’s Vale':[76,75],'The Old Road':[51,16]};return `<div class="hero"><div class="kicker">THE GRAVEN MARCH</div><h2>The map is mostly bad news.</h2><p>Threats rise when ignored. When a region breaks, contracts get harder, trade gets worse, and settlements can disappear.</p></div><div class="map">${Object.entries(pos).map(([n,p])=>`<div class="place ${n!=='Greyhaven'&&state.threats[n]>45?'dangerp':''}" style="left:${p[0]}%;top:${p[1]}%"><b>${n==='Greyhaven'?'🏚️':n==='Blackpine Forest'?'🌲':n==='Drowned Farms'?'🌾':n==='Redfang Hills'?'⛰️':n==='Saint Orrin’s Vale'?'⛪':'🛣️'}</b>${n}</div>`).join('')}</div><div class="sectionTitle"><h3>Regional Threat</h3><span>0 safe • 100 lost</span></div>${Object.entries(state.threats).map(([k,v])=>`<div class="card" style="margin-bottom:6px"><div class="statline"><b>${k}</b><span class="${v>60?'danger':v<30?'good':''}">${Math.round(v)}%</span></div><div class="bar threat"><i style="width:${v}%"></i></div></div>`).join('')}`}
function renderVault(){return `<div class="hero"><div class="kicker">ARMORY & VAULT</div><h2>Everything has a price.</h2><p>Most loot buys soup and bandages. Some things should have stayed buried.</p></div><div class="sectionTitle"><h3>Loot Caches</h3><span>${state.caches.length}</span></div><div class="grid2">${state.caches.length?state.caches.map((c,i)=>`<div class="card cache"><div class="chest">🧰</div><b>${c.name}</b><div class="small muted">Recovered from ${c.from}</div><div class="actions"><button class="btn goldbtn openCache" data-cache="${i}">Open</button></div></div>`).join(''):'<div class="empty" style="grid-column:1/-1">No unopened caches.</div>'}</div><div class="sectionTitle"><h3>Legendary Artifacts</h3><span>${state.artifacts.length}</span></div><div class="list">${state.artifacts.length?state.artifacts.map(a=>`<div class="card"><div style="font-size:30px">${a.icon}</div><b>${a.name}</b><p class="small">${a.desc}</p><div class="small danger">Cost: ${a.cost}</div></div>`).join(''):'<div class="empty">Nothing legendary. Yet.</div>'}</div><div class="sectionTitle"><h3>Inventory</h3><span>${state.inventory.reduce((s,x)=>s+(x.qty||1),0)} items</span></div><div class="list">${state.inventory.map((x,i)=>`<div class="card statline"><span>${x.name}</span><span class="muted">${x.type}${x.qty?` ×${x.qty}`:''}</span></div>`).join('')||'<div class="empty">Empty.</div>'}</div>`}
function wire(){
 document.querySelectorAll('.hire').forEach(b=>b.onclick=()=>hire(b.dataset.id));
 document.querySelectorAll('.inspect').forEach(b=>b.onclick=()=>inspectRecruit(b.dataset.id));
 document.querySelectorAll('.partyEdit').forEach(b=>b.onclick=()=>editParty(b.dataset.party));
 document.querySelectorAll('.take').forEach(b=>b.onclick=()=>chooseParty(b.dataset.contract));
 document.querySelectorAll('.contractInfo').forEach(b=>b.onclick=()=>inspectContract(b.dataset.contract));
 document.querySelectorAll('.advance').forEach(b=>b.onclick=()=>advanceExpedition(b.dataset.party,true));
 document.querySelectorAll('.upgrade').forEach(b=>b.onclick=()=>upgrade(b.dataset.up));
 document.querySelectorAll('.info').forEach(b=>b.onclick=()=>infoHQ(b.dataset.info));
 document.querySelectorAll('.openCache').forEach(b=>b.onclick=()=>openCache(+b.dataset.cache));
 const rr=document.getElementById('refreshRecruits');if(rr)rr.onclick=()=>{if(state.silver<4)return toast('Need 4 silver.');state.silver-=4;state.recruits=Array.from({length:6},recruitGen);toast('New faces drift in.');render()};
 const reset=document.getElementById('reset');if(reset)reset.onclick=()=>{modal(`<div class="sheetHead"><h3>Burn the ledger?</h3><button class="x" onclick="closeModal()">✕</button></div><p class="small muted">This erases the company and starts Day 1 again.</p><div class="actions"><button class="btn primary" id="confirmReset">Reset Everything</button></div>`);setTimeout(()=>{const c=document.getElementById('confirmReset');if(c)c.onclick=()=>{localStorage.removeItem(SAVE);state=initial();closeModal();render()}},0)}
}
function hire(id){const r=state.recruits.find(x=>x.id===id);if(!r||employedCount()>=cap()||state.silver<r.hire)return;state.silver-=r.hire;state.roster.push(r);state.recruits=state.recruits.filter(x=>x.id!==id);state.log.push(`Hired ${r.name}, ${r.race.toLowerCase()} ${r.bg.toLowerCase()}, for ${r.hire}s.`);toast(`${r.name} hired.`);render()}
function inspectRecruit(id){const r=state.roster.find(x=>x.id===id);if(!r)return;modal(`<div class="sheetHead"><div><h3>${RACES[r.race]} ${r.name}</h3><div class="small muted">${r.race} ${r.bg} • Level ${r.lvl} • ${r.status}</div></div><button class="x" onclick="closeModal()">✕</button></div><div class="grid2">${Object.entries(r.stats).map(([k,v])=>`<div class="card"><div class="tiny muted">${k.toUpperCase()}</div><b>${v}</b></div>`).join('')}</div><div class="sectionTitle"><h3>Condition</h3><span>${r.hp}/${r.maxHp} HP</span></div><div class="hpbar"><i style="width:${r.hp/r.maxHp*100}%"></i></div>${r.injury?`<p class="danger small">${r.injury} • ${r.recovery} day(s) recovery</p>`:''}<div class="sectionTitle"><h3>Experience</h3><span>${r.xp}/${r.xpNext}</span></div><div class="bar goldbar"><i style="width:${r.xp/r.xpNext*100}%"></i></div><div class="sectionTitle"><h3>Equipment</h3></div><div class="card small">Weapon: <b>${r.gear.weapon}</b><br>Armor: <b>${r.gear.armor}</b></div><div class="sectionTitle"><h3>Record</h3></div><div class="card small">Missions: ${r.missions}<br>Kills: ${r.kills}<br>Scars: ${r.scars.length?r.scars.join(', '):'None'}</div>`)}
function editParty(pid){const p=state.parties.find(x=>x.id===pid);if(!p)return;modal(`<div class="sheetHead"><h3>${p.name}</h3><button class="x" onclick="closeModal()">✕</button></div><p class="small muted">Choose up to 4 ready adventurers.</p>${state.roster.map(r=>{let assignedElsewhere=state.parties.some(q=>q.id!==p.id&&q.members.includes(r.id));let checked=p.members.includes(r.id);return `<div class="toggleRow"><div><b>${RACES[r.race]} ${r.name}</b><div class="tiny muted">Lv.${r.lvl} ${r.bg} • ${r.status}</div></div><button class="btn toggleMember" data-rid="${r.id}" ${assignedElsewhere||r.status!=='Ready'?'disabled':''}>${checked?'Remove':'Add'}</button></div>`}).join('')||'<div class="empty">Hire somebody first.</div>'}`);document.querySelectorAll('.toggleMember').forEach(b=>b.onclick=()=>{let i=p.members.indexOf(b.dataset.rid);if(i>=0)p.members.splice(i,1);else if(p.members.length<4)p.members.push(b.dataset.rid);else return toast('Party is full.');closeModal();render();editParty(pid)})}
function inspectContract(id){const c=state.contracts.find(x=>x.id===id);if(!c)return;modal(`<div class="sheetHead"><h3>${c.title}</h3><button class="x" onclick="closeModal()">✕</button></div><p>${c.desc}</p><div class="card small">Location: ${c.place}<br>Distance: ${c.distance} miles<br>Reward: ${c.reward}s${c.cache?' + recovered cache':''}<br>Estimated risk: ${c.risk}/4<br>Unknown factors: ${Math.max(0,c.unknown-(state.hq['Occult Archive']||0))}</div><p class="small muted">Possible reported threats: ${c.enemies.slice(0,Math.max(1,2-(state.hq['Occult Archive']||0))).join(', ')}${c.unknown?' • reports incomplete':''}</p>`)}
function chooseParty(cid){const c=state.contracts.find(x=>x.id===cid);let idle=state.parties.filter(p=>!p.expedition&&p.members.length);if(!idle.length)return toast('No staffed idle party.');modal(`<div class="sheetHead"><h3>Send a party</h3><button class="x" onclick="closeModal()">✕</button></div><p class="small muted">${c.title} • Risk ${c.risk}/4</p>${idle.map(p=>`<button class="btn choice dispatch" data-party="${p.id}"><b>${p.name}</b><br><span class="tiny">${p.members.length} members • Power ${Math.round(totalPower(p))}</span></button>`).join('')}`);document.querySelectorAll('.dispatch').forEach(b=>b.onclick=()=>dispatch(cid,b.dataset.party))}
