/* Broken Lantern v11 visual asset integration. Generated art is static game content; no model runs at play time. */
const BL_ART={characters:BL_ART_DATA.characters,environments:BL_ART_DATA.environments,icons:BL_ART_DATA.icons,caches:BL_ART_DATA.caches,title:BL_ART_DATA.title};
const BL_PORTRAIT_POOLS={
 Human:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,66,67,70,72,73,74],
 Dwarf:[24,25,26,27,28,29,30,31,32,33,34,35,69],
 Elf:[36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,68],
 Orc:[54,55,56,57,58,59,60,61,62,63,64,65,71]
};
const BL_ENEMY_ART={
 Goblin:[75,76],Hobgoblin:[77],Ghoul:[78],Wight:[79],Undead:[78,79],Wolf:[80],
 'Dire Wolf':[81],Werewolf:[81],Ogre:[82]
};
const BL_ICON_CELLS={
 hq:[0,0],roster:[1,0],party:[2,0],contracts:[3,0],world:[4,0],market:[5,0],
 vault:[0,1],silver:[1,1],prosperity:[2,1],stability:[3,1],threat:[4,1],injury:[5,1],
 healing:[0,2],info:[1,2],menu:[2,2],audio:[3,2],music:[4,2],newgame:[5,2]
};
function blHash(s){let h=2166136261;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function blAtlasPos(index,cols,rows){const c=index%cols,r=Math.floor(index/cols);return`${cols===1?0:c/(cols-1)*100}% ${rows===1?0:r/(rows-1)*100}%`}
function blPortraitPool(a){return a&&a.culture==='Veyric'?BL_PORTRAIT_POOLS[a.race]:null}
function ensurePortrait(a){const pool=blPortraitPool(a);if(!pool?.length)return null;if(Number.isInteger(a.portraitV11)&&pool.includes(a.portraitV11))return a.portraitV11;const i=pool[blHash(`${a.id}|${a.name}|${a.race}`)%pool.length];a.portraitV11=i;return i}
function blPortraitHTML(a,cls=''){const i=ensurePortrait(a);if(i==null)return raceGlyph(a?.race||'Human');return`<span class="blPortrait ${cls}" aria-label="${esc(a.name)} portrait" style="background-image:url('${BL_ART.characters}');background-position:${blAtlasPos(i,12,7)}"></span>`}
function blEnemyPortrait(u){const pool=BL_ENEMY_ART[u.species];if(!pool?.length)return`<span class="enemyGlyph">${esc((u.species||'?').slice(0,2).toUpperCase())}</span>`;const i=pool[blHash(`${u.id||u.name}|${u.name}`)%pool.length];return`<span class="blPortrait blEnemyPortrait" style="background-image:url('${BL_ART.characters}');background-position:${blAtlasPos(i,12,7)}"></span>`}
function blIcon(name,cls=''){const p=BL_ICON_CELLS[name];if(!p)return typeof v10Icon==='function'?v10Icon(name):'';const [c,r]=p;return`<span class="blArtIcon ${cls}" aria-hidden="true" style="background-image:url('${BL_ART.icons}');background-position:${c/5*100}% ${r/2*100}%"></span>`}
function blCacheArt(rarity,cls=''){const r=clamp(Number(rarity)||0,0,4);return`<span class="blCacheArt ${cls}" style="background-image:url('${BL_ART.caches}');background-position:${r/4*100}% 0%"></span>`}
function blScenePos(c,r){return`${c*100}% ${r*100}%`}
function blApplyHeroArt(){if(!state||state.currentRegion!=='veyric')return;const hero=document.querySelector('#app .hero');if(!hero)return;const pos={hq:[1,0],roster:[0,0],contracts:[1,1],world:[0,0],vault:[0,1]}[state.ui.tab]||[0,0];hero.classList.add('blHeroArt');hero.style.setProperty('--bl-scene',`url('${BL_ART.environments}')`);hero.style.setProperty('--bl-pos',blScenePos(pos[0],pos[1]));}
function blApplyCacheCards(){document.querySelectorAll('[data-action="openCache"]').forEach(btn=>{if(btn.querySelector('.blCacheArt'))return;const c=state?.caches?.find(x=>x.id===btn.dataset.id);if(!c)return;btn.insertAdjacentHTML('afterbegin',blCacheArt(c.rarity,'blCacheThumb'))})}
function blPostProcess(){blApplyHeroArt();blApplyCacheCards();}

NAV.splice(0,NAV.length,['hq',blIcon('hq'),'HQ'],['roster',blIcon('roster'),'ROSTER'],['contracts',blIcon('contracts'),'CONTRACTS'],['world',blIcon('world'),'WORLD'],['vault',blIcon('vault'),'VAULT']);
topbar=function(){const r=region();return`<div class="topbar"><div class="toprow"><div class="brand"><h1>${esc(state.company.name)}</h1><small>${esc(REGION_DEFS[state.currentRegion].name)} • Day ${state.company.day}</small></div><button class="iconbtn" data-action="audio" title="Audio">${blIcon('audio')}</button><button class="iconbtn" data-action="menu" title="Game menu">${blIcon('menu')}</button></div><div class="resources"><div class="res">Silver<b>${Math.round(state.company.silver)}</b></div><div class="res">Renown<b>${state.company.renown}</b></div><div class="res">Roster<b>${localRoster().length}/${rosterCap()}</b></div><div class="res">Threat<b>${Math.round(r.threat)}%</b></div></div></div>`};

rosterCard=function(a){const d=derived(a),pct=clamp(a.hp/d.maxHp*100,0,100);return`<button class="card member blMember" data-action="inspect" data-id="${a.id}"><div class="portrait blPortraitFrame">${blPortraitHTML(a)}</div><div style="text-align:left"><div class="statline"><h4>${esc(a.name)}</h4><span>Lv.${a.lvl}</span></div><div class="small muted">${esc(a.race)} • <b class="gold">${esc(a.culture)} ${esc(a.className)}</b></div><div class="tiny muted">${esc(a.background)} • ${esc(a.status)} • ${a.hp}/${d.maxHp} HP</div><div class="hpbar"><i style="width:${pct}%"></i></div><div class="tags">${(a.traits||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><span class="tiny">›</span></button>`};
recruitCard=function(a){const d=derived(a);return`<div class="card member blMember"><div class="portrait blPortraitFrame">${blPortraitHTML(a)}</div><div><h4>${esc(a.name)}</h4><div class="small muted">Lv.${a.lvl} ${esc(a.race)} • <b class="gold">${esc(a.culture)} ${esc(a.className)}</b></div><div class="tiny muted">${esc(a.background)} • ${a.wage}s/week • ${d.maxHp} HP</div><div class="tags">${a.traits.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div><button class="btn ghost" data-action="inspectRecruit" data-id="${a.id}">ⓘ</button><button class="btn goldbtn" data-action="hire" data-id="${a.id}">Hire ${a.wage*3}s</button></div></div>`};
partyCard=function(p){const ms=partyMembers(p),cap=partyCap(p.regionId),captain=state.roster.find(a=>a.id===p.captainId);return`<div class="card partyCard"><div class="statline"><div><b>${esc(p.name)}</b><div class="tiny muted">${captain?`Captain ${esc(captain.name)} • `:''}${p.missions} missions • ${p.wins} wins${p.specialty?` • ${esc(p.specialty)}`:''}</div></div><span>${ms.length}/${cap}</span></div><div class="faces">${ms.map(a=>{const d=derived(a);return`<div class="face blPartyFace" title="${esc(a.name)} • ${a.hp}/${d.maxHp} HP">${blPortraitHTML(a,'blFacePortrait')}<small>${a.lvl}</small></div>`}).join('')||'<span class="small muted">Empty party</span>'}</div><div class="cohesion">Cohesion ${p.cohesion}/100</div><div class="tactics">${['Cautious','Balanced','Aggressive'].map(t=>`<button class="tactic ${p.tactic===t?'active':''}" data-action="tactic" data-id="${p.id}" data-value="${t}" ${p.expedition?'disabled':''}>${t}</button>`).join('')}</div><div class="actions"><button class="btn" data-action="editParty" data-id="${p.id}" ${p.expedition?'disabled':''}>Assign Members</button>${p.expedition?`<button class="btn primary" data-action="nav" data-tab="contracts">Monitor</button>`:''}</div></div>`};
renderModalParty=function(pid){const p=state.parties.find(x=>x.id===pid);if(!p)return;const cap=partyCap(p.regionId);modal(`<div class="sheetHead"><div><h3>${esc(p.name)}</h3><div class="tiny muted">${p.members.length}/${cap} • Cohesion ${p.cohesion}</div></div><button class="x" data-action="close">✕</button></div><div class="notice">Health and injuries are shown here so you can choose a field-ready party without memorizing the roster.</div><div class="list blPartyPicker" style="margin-top:8px">${localRoster(p.regionId).filter(a=>a.status==='Ready'||p.members.includes(a.id)).map(a=>{const inP=p.members.includes(a.id),other=state.parties.some(q=>q.id!==p.id&&q.members.includes(a.id)),d=derived(a),pct=clamp(a.hp/d.maxHp*100,0,100);return`<div class="card blPickCard"><div class="blPickIdentity"><div class="portrait blPickPortrait">${blPortraitHTML(a)}</div><div class="blPickMeta"><b>${esc(a.name)}</b><div class="tiny muted">${esc(a.culture)} ${esc(a.className)} • Lv.${a.lvl}</div><div class="tiny ${pct<45?'danger':'muted'}">${a.hp}/${d.maxHp} HP${a.injury?` • ${esc(a.injury)} • ${a.recovery}d`:''}</div><div class="hpbar"><i style="width:${pct}%"></i></div></div></div><div class="blPickActions"><button class="btn" data-action="toggleMember" data-party="${p.id}" data-id="${a.id}" ${other?'disabled':''}>${inP?'Remove':'Add'}</button>${inP?`<button class="btn ghost" data-action="captain" data-party="${p.id}" data-id="${a.id}">${p.captainId===a.id?'Captain':'Make Captain'}</button>`:''}</div></div>`}).join('')}</div>`)};

const _renderInspectV11=renderInspect;
renderInspect=function(id,recruit=false){_renderInspectV11(id,recruit);const a=(recruit?region().recruits:state.roster).find(x=>x.id===id);if(!a)return;const sheet=document.getElementById('sheet');const head=sheet?.querySelector('.sheetHead');if(head&&ensurePortrait(a)!=null){head.insertAdjacentHTML('afterend',`<div class="blInspectPortrait">${blPortraitHTML(a,'blPortraitLarge')}<div><b>${esc(a.name)}</b><div class="small muted">${esc(a.race)} • ${esc(a.culture)} ${esc(a.className)}</div></div></div>`)} };

unitHTML=function(u){let mark;if(u.charId){const a=state.roster.find(x=>x.id===u.charId);mark=a?blPortraitHTML(a,'blCombatPortrait'):raceGlyph(u.race||'Human')}else mark=blEnemyPortrait(u);return`<div class="unit ${u.hp<=0?'dead':''} ${u.legendary?'unitLegendary':''}"><div class="unitTop"><span class="unitIdentity">${mark}<b>${esc(u.name)}</b></span><span>${Math.max(0,Math.round(u.hp))}/${u.maxHp}</span></div><div class="hpbar"><i style="width:${clamp(u.hp/u.maxHp*100,0,100)}%"></i></div></div>`};

renderStart=function(){document.body.dataset.region='start';document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="start"><div class="startPanel blStartPanel"><div class="blStartArt" style="background-image:url('${BL_ART.title}')" role="img" aria-label="The Broken Lantern"></div><div class="blStartForm"><p>Build an adventuring company in a world where civilization survives by paying people like you to walk outside the walls.</p><div class="label">Name your company</div><input id="companyName" class="field" maxlength="32" placeholder="e.g. The Black Hounds"><button class="btn primary wide" data-action="begin">FOUND COMPANY</button><p class="tiny muted">You begin in Greyhaven, in the Graven March of the Veyric Marches.</p></div></div></div>`;document.getElementById('nav').innerHTML=''};

const _renderV11Art=render;
render=function(){_renderV11Art();if(state){blPostProcess();save()}};
const _renderMarketV11=renderMarket;
renderMarket=function(){_renderMarketV11();if(state?.currentRegion==='veyric'){const sheet=document.getElementById('sheet');sheet?.insertAdjacentHTML('afterbegin',`<div class="blMarketBanner" style="--bl-scene:url('${BL_ART.environments}');--bl-pos:${blScenePos(0,1)}"></div>`)}};
const _openCacheV11=openCache;
openCache=function(id){const c=state.caches.find(x=>x.id===id);_openCacheV11(id);if(c){document.getElementById('sheet')?.insertAdjacentHTML('afterbegin',blCacheArt(c.rarity,'blCacheReveal'))}};
const _showReportV11=showReport;
showReport=function(r){_showReportV11(r);if(r?.cache)document.getElementById('sheet')?.insertAdjacentHTML('afterbegin',blCacheArt(r.cache.rarity,'blCacheReveal'))};

showMenu=function(){modal(`<div class="sheetHead"><h3>${blIcon('menu')} Game Menu</h3><button class="x" data-action="close">✕</button></div><div class="list"><button class="card" data-action="audio"><b>${blIcon('audio')} Audio</b><div class="tiny muted">Music and effects volumes</div></button><button class="card" data-action="backup"><b>${typeof v10Icon==='function'?v10Icon('save'):''} Save & Backup</b><div class="tiny muted">Copy or restore your company save</div></button><button class="card dangerBtn" data-action="newGame"><b>${blIcon('newgame')} New Game</b><div class="tiny">Permanently replace this company</div></button></div>`)};

const _auditV11=audit;
audit=function(){const out=_auditV11();out.v11Visuals=true;out.v11PortraitPools=Object.fromEntries(Object.entries(BL_PORTRAIT_POOLS).map(([k,v])=>[k,v.length]));out.v11EnemyPortraitSpecies=Object.keys(BL_ENEMY_ART).length;out.v11ArtFallbacks=true;return out};
window.__BL_AUDIT=audit;