function localInventory(regionId=state.currentRegion){return state.inventory.filter(x=>x.regionId===regionId)}

function refreshMarket(regionId,force=false){const r=state.regions[regionId];if(!force&&state.company.day<r.market.nextRefresh)return;const count=clamp(4+Math.floor(r.prosperity/12)+(hasArtifact('The Salt Crown',regionId)?1:0),4,14);r.market.stock=[];for(let i=0;i<count;i++){let ri=itemRarityFrom(regionId,1,true);if(r.prosperity<35)ri=Math.min(ri,1);if(r.prosperity<55)ri=Math.min(ri,2);if(r.prosperity<75)ri=Math.min(ri,3);const item=generateItem(regionId,ri);r.market.stock.push({id:uid('m'),item,price:itemPrice(item,regionId)})}r.market.nextRefresh=state.company.day+3}
function refreshRecruits(regionId){const r=state.regions[regionId];const count=clamp(2+Math.floor(r.stability/12)+(state.company.renown>50?1:0),2,12);r.recruits=Array.from({length:count},()=>generateAdventurer(regionId))}
function contractRisk(regionId){const t=state.regions[regionId].threat;let base=t<25?1:t<45?2:t<65?3:t<82?4:5;return clamp(base+rnd(-1,1),1,5)}
function pickEnemySpecies(regionId){const d=REGION_DEFS[regionId];return chance(.58)?d.common:pick(d.enemies)}
function createNemesis(regionId,species,level){const n={id:uid('n'),name:`${pick(NEMESIS_FIRST)} ${pick(NEMESIS_TITLES)}`,species,regionId,level:Math.max(2,level),notoriety:1,alive:true,history:[]};state.nemeses.push(n);return n}
function generateContract(regionId){const r=state.regions[regionId],risk=contractRisk(regionId),species=pickEnemySpecies(regionId),type=pick(CONTRACT_TYPES),countBase=[[2,4],[3,5],[5,8],[7,11],[10,16]][risk-1];let enemyCount=rnd(countBase[0],countBase[1])+(r.threat>82?1:0)+(r.threat>92?2:0);enemyCount=clamp(enemyCount,2,18);let nemesis=null;const active=state.nemeses.filter(n=>n.regionId===regionId&&n.alive&&n.species===species);if(risk>=4&&active.length&&chance(.28))nemesis=pick(active);else if(risk>=4&&chance(.12))nemesis=createNemesis(regionId,species,risk);const title=nemesis?`${nemesis.name}: ${type[0]}`:pick(CONTRACT_NAMES[species]||[`${species} Trouble`]);const office=hq(regionId).upgrades['Contract Office']||0;const basePay=Math.round((12+risk*14+enemyCount*2)*(1+office*.05)*(1+r.prosperity*.002));return{id:uid('c'),regionId,type:type[0],check:type[2],title,desc:`${type[1]} Expected opposition: ${species}${enemyCount>9?' in force':''}.`,species,risk,enemyCount,reward:basePay,unknown:Math.max(0,risk-rnd(0,hq(regionId).upgrades['Occult Archive']||0)),expires:state.company.day+rnd(3,7),nemesisId:nemesis?.id||null,cacheChance:clamp(.35+risk*.08,0,.8)}}
function refreshContracts(regionId){const r=state.regions[regionId],count=5+(hq(regionId).upgrades['Contract Office']||0);r.contracts=r.contracts.filter(c=>c.expires>=state.company.day);while(r.contracts.length<count)r.contracts.push(generateContract(regionId))}
function refreshRegion(regionId,force=false,sOverride=null){const prev=state;if(sOverride)state=sOverride;try{refreshMarket(regionId,force);if(force||!state.regions[regionId].recruits.length)refreshRecruits(regionId);refreshContracts(regionId)}finally{if(sOverride)state=prev}}

function pushHistory(text,regionId=state.currentRegion){state.history.push({day:state.company.day,regionId,text});if(state.history.length>500)state.history.splice(0,state.history.length-500);state.regions[regionId]?.log.push(`Day ${state.company.day} — ${text}`);if(state.regions[regionId]?.log.length>80)state.regions[regionId].log.shift()}
function processWorldDay(){
 REGION_ORDER.forEach(id=>{const r=state.regions[id];let threatDrift=r.hq.established?rnd(0,2):rnd(1,3);r.threat=clamp(r.threat+threatDrift,0,100);if(r.threat>70){r.prosperity=clamp(r.prosperity-rnd(0,2),0,100);r.stability=clamp(r.stability-rnd(0,2),0,100)}if(hasArtifact('The Salt Crown',id)&&chance(.45))r.stability=clamp(r.stability-1,0,100);else if(r.threat<35){if(chance(.55))r.prosperity=clamp(r.prosperity+1,0,100);if(chance(.45))r.stability=clamp(r.stability+1,0,100)}if(r.threat>=95&&r.settlements>1&&chance(.16)){r.settlements--;r.stability=clamp(r.stability-6,0,100);r.prosperity=clamp(r.prosperity-5,0,100);pushHistory(`${REGION_DEFS[id].name}: a settlement was lost to unchecked threats.`,id)}if(r.settlements<=1)r.lost=true;refreshMarket(id);refreshContracts(id)});
}
function recoveryDay(){state.roster.forEach(a=>{if(a.status!=='Recovering'||a.recovery<=0)return;const inf=hq(a.regionId).upgrades.Infirmary||0,hard=(a.traits||[]).includes('Hard Worker')?3:0;a.recovery=Math.max(0,a.recovery-1);a.hp=Math.min(a.maxHp,a.hp+10+inf*5+hard);if(a.recovery===0){a.status='Ready';a.injury=null;pushHistory(`${a.name} returned to duty.`,a.regionId)}})}
function trainingDay(){state.roster.forEach(a=>{if(a.status==='Ready'){const lv=hq(a.regionId).upgrades['Training Yard']||0;if(lv)grantXP(a,lv*2)}})}
function weeklyWages(){if(state.company.day%7!==0)return;let total=0;REGION_ORDER.forEach(id=>{if(!hq(id).established)return;const stores=hq(id).upgrades.Stores||0;const base=state.roster.filter(a=>a.regionId===id&&a.status!=='Dead').reduce((s,a)=>s+a.wage,0);total+=Math.ceil(base*(1-stores*.04)*(hasArtifact("The King’s Second Face",id)?1.08:1))});state.company.silver-=total;pushHistory(`Weekly wages and upkeep cost ${money(total)}.`);if(state.company.silver<0){state.company.renown=Math.max(0,state.company.renown-3);pushHistory('The treasury fell below zero. Company reputation suffered.')}}
function relationshipDay(){const active=state.roster.filter(a=>a.status!=='Dead');if(active.length<2||!chance(.4))return;const a=pick(active),candidates=active.filter(b=>b.id!==a.id&&b.regionId===a.regionId);if(!candidates.length)return;const b=pick(candidates);let delta=rnd(-2,4);if(a.traits.includes('Kindhearted')||b.traits.includes('Kindhearted'))delta+=1;if((a.traits.includes('Hot Temper')&&b.traits.includes('Stubborn'))||(b.traits.includes('Hot Temper')&&a.traits.includes('Stubborn')))delta-=3;const before=relValue(a.id,b.id),after=clamp(before+delta,-100,100);setRel(a.id,b.id,after);const oldL=relLabel(before),newL=relLabel(after);if(oldL!==newL){pushHistory(`${a.name} and ${b.name} became ${newL.toLowerCase()}.`,a.regionId);a.history.push(`Day ${state.company.day}: ${newL} with ${b.name}.`);b.history.push(`Day ${state.company.day}: ${newL} with ${a.name}.`)}}
function advanceDay(reason='A day passes.'){state.company.day++;recoveryDay();trainingDay();weeklyWages();processWorldDay();relationshipDay();REGION_ORDER.forEach(id=>{if(state.company.day%3===0)refreshRecruits(id)});pushHistory(reason);save()}
