function finishExpedition(p){const e=p.expedition,c=e.contract,r=state.regions[c.regionId],win=e.battleWon!==false;const members=p.members.map(id=>state.roster.find(a=>a.id===id)).filter(Boolean);let pay=0,loot=null,cache=null,artifact=null;if(win){pay=Math.round(c.reward*(1+(e.payBonus||0))*(hasArtifact("The King’s Second Face",c.regionId)?1.25:1));members.forEach(a=>{const d=derived(a);pay=Math.round(pay*(1+d.special.pay))});state.company.silver+=pay;state.company.renown+=c.risk;const threatDrop=rnd(4,8)+c.risk;r.threat=clamp(r.threat-threatDrop,0,100);r.stability=clamp(r.stability+rnd(0,2),0,100);if(['Escort','Caravan','Defense'].includes(c.type))r.prosperity=clamp(r.prosperity+rnd(1,3),0,100);const arm=hq(c.regionId).upgrades.Armory||0;if(chance(.22+arm*.08)){let ri=itemRarityFrom(c.regionId,c.risk,false);ri=clamp(ri+Math.floor(arm/3),0,4);loot=generateItem(c.regionId,ri);inventoryEntry(loot,c.regionId,1)}if(chance(c.cacheChance)){let ri=clamp(itemRarityFrom(c.regionId,c.risk,false),0,4);cache={id:uid('cache'),name:`${RARITIES[ri]} Field Cache`,rarity:ri,regionId:c.regionId,from:c.title};state.caches.push(cache)}const archive=hq(c.regionId).upgrades['Occult Archive']||0,vault=hq(c.regionId).upgrades['Artifact Vault']||0,localArts=state.artifacts.filter(a=>a.regionId===c.regionId).length,cap=vault?99:2;if(c.risk>=4&&localArts<cap&&chance(.015+c.risk*.012+archive*.012)){const avail=ARTIFACT_POOL.filter(x=>!state.artifacts.some(a=>a.name===x.name));const proto=pick(avail.length?avail:ARTIFACT_POOL);if(proto){artifact={id:uid('art'),regionId:c.regionId,...proto};state.artifacts.push(artifact);pushHistory(`Recovered artifact: ${artifact.name}.`,c.regionId)}}if(ENEMY_SPECIES[c.species]?.supernatural&&hasArtifact('Saint Veyra’s Nail',c.regionId)){members.filter(a=>a.status!=='Dead').forEach(a=>{if(chance(.08)&&!a.traits.includes('Haunted')){a.traits.push('Haunted');a.history.push(`Day ${state.company.day}: Saint Veyra’s Nail left them Haunted.`)}})}p.wins++;p.enemyWins=p.enemyWins||{};p.enemyWins[c.species]=(p.enemyWins[c.species]||0)+1;if((p.enemyWins[c.species]||0)>=5&&p.specialty!==`${c.species} Hunters`){p.specialty=`${c.species} Hunters`;pushHistory(`${p.name} earned the specialty ${p.specialty}.`,c.regionId)}sfx('success')}else{r.threat=clamp(r.threat+rnd(4,9),0,100);r.stability=clamp(r.stability-rnd(1,4),0,100);sfx('fail')}
 p.missions++;p.cohesion=clamp(p.cohesion+(win?3:1),0,100);members.forEach(a=>{a.missions++;grantXP(a,win?18+c.risk*12:8+c.risk*5);if(a.status==='Expedition')a.status='Ready'});relationshipAfterMission(p,e.deaths||[]);const nem=c.nemesisId?state.nemeses.find(n=>n.id===c.nemesisId):null;if(nem){if(win){nem.alive=false;nem.history.push(`Killed by ${p.name} on Day ${state.company.day}.`);pushHistory(`${nem.name}, ${nem.species} nemesis, was killed by ${p.name}.`,c.regionId)}else{nem.level++;nem.notoriety++;nem.history.push(`Defeated ${p.name} on Day ${state.company.day}.`);pushHistory(`${nem.name} grew more notorious after defeating ${p.name}.`,c.regionId)}}pushHistory(`${p.name} ${win?'completed':'failed'} ${c.title}${pay?` for ${money(pay)}`:''}.`,c.regionId);const report={title:c.title,win,pay,loot,cache,artifact,deaths:e.deaths||[],regionId:c.regionId};p.members=p.members.filter(id=>state.roster.some(a=>a.id===id&&a.status!=='Dead'));p.expedition=null;advanceDay(`${p.name} returned from ${c.title}.`);save();showReport(report)}
function advanceExpedition(pid,manual=false){const p=state.parties.find(x=>x.id===pid);if(!p||!p.expedition)return;const e=p.expedition;if(e.battle)return combatRound(p);e.step++;e.progress=clamp(e.progress+rnd(12,21),0,100);if(e.progress<62&&(!e.lastCheck||e.step-e.lastCheck>=2)&&chance(.62)){fieldCheck(p);e.lastCheck=e.step}else if(e.progress<68)e.events.push(`${e.progress}% — The party pushes deeper into hostile ground.`);if(e.progress>=68&&!e.fought){startBattle(p);render();return}if(e.progress>=100&&e.fought)return finishExpedition(p);save();render()}

function openCache(id){const c=state.caches.find(x=>x.id===id);if(!c)return;const item=generateItem(c.regionId,c.rarity);inventoryEntry(item,c.regionId,1);state.caches=state.caches.filter(x=>x.id!==id);sfx('loot');save();modal(`<div class="sheetHead"><h3>Cache Opened</h3><button class="x" data-action="close">✕</button></div>${itemHTML(item)}<div class="notice">This ${RARITIES[item.rarity]} item has exactly ${item.mods.length} modifier${item.mods.length===1?'':'s'}.</div>`)}

function marketQualityText(p){if(p<30)return'Poor — mostly Common';if(p<50)return'Strained — Uncommon appears';if(p<70)return'Healthy — Rare possible';if(p<85)return'Wealthy — Super Rare possible';return'Exceptional — Legendary sightings possible'}
function stabilityText(s){if(s<25)return'Collapsing';if(s<45)return'Unsteady';if(s<65)return'Holding';if(s<82)return'Stable';return'Thriving'}
function threatText(t){if(t<25)return'Low';if(t<45)return'Dangerous';if(t<65)return'Severe';if(t<82)return'Critical';return'Catastrophic'}

function topbar(){const r=region();return`<div class="topbar"><div class="toprow"><div class="brand"><h1>${esc(state.company.name)}</h1><small>${esc(REGION_DEFS[state.currentRegion].name)} • Day ${state.company.day}</small></div><button class="iconbtn" data-action="audio" title="Audio">${state.settings.sfx?'🔊':'🔇'}</button><button class="iconbtn" data-action="menu" title="Game menu">☰</button></div><div class="resources"><div class="res">Silver<b>${Math.round(state.company.silver)}</b></div><div class="res">Renown<b>${state.company.renown}</b></div><div class="res">Roster<b>${localRoster().length}/${rosterCap()}</b></div><div class="res">Threat<b>${Math.round(r.threat)}%</b></div></div></div>`}
function navHTML(){return NAV.map(([id,ic,l])=>`<button class="navbtn ${state.ui.tab===id?'active':''}" data-action="nav" data-tab="${id}"><b>${ic}</b>${l}</button>`).join('')}
function render(){if(!state)return renderStart();const app=document.getElementById('app');app.className='app';app.innerHTML=topbar()+`<div class="screen">${state.ui.tab==='hq'?renderHQ():state.ui.tab==='roster'?renderRoster():state.ui.tab==='contracts'?renderContracts():state.ui.tab==='world'?renderWorld():renderVault()}</div>`;document.getElementById('nav').innerHTML=navHTML();save()}
function renderStart(){document.getElementById('app').className='';document.getElementById('app').innerHTML=`<div class="start"><div class="startPanel"><div class="startMark">🏮</div><h1>The Broken Lantern</h1><p>Build an adventuring company in a world where civilization survives by paying people like you to walk outside the walls.</p><div class="label">Name your company</div><input id="companyName" class="field" maxlength="32" placeholder="e.g. The Black Hounds"><button class="btn primary wide" data-action="begin">FOUND COMPANY</button><p class="tiny muted">You begin in Greyhaven, in the Graven March of the Veyric Marches.</p></div></div>`;document.getElementById('nav').innerHTML=''}

function renderHQ(){const r=region(),d=regionDef(),active=localParties().filter(p=>p.expedition),recovering=localRoster().filter(a=>a.status==='Recovering');return`<div class="hero"><div class="kicker">${esc(d.name.toUpperCase())} • ${esc(d.culture.toUpperCase())}</div><h2>${esc(r.hq.name)}</h2><p>${esc(d.desc)}</p></div>
<div class="grid3"><button class="card" data-action="market"><b>🛒 Market</b><div class="tiny muted">${marketQualityText(r.prosperity)}</div></button><button class="card" data-action="rest"><b>🌙 Rest Day</b><div class="tiny muted">Advances recovery and world simulation</div></button><button class="card" data-action="facilities"><b>ⓘ Systems</b><div class="tiny muted">See exact HQ effects</div></button></div>
${recovering.length?`<div class="sectionTitle"><h3>Recovering</h3><span>1 day passes per contract or Rest Day</span></div><div class="list">${recovering.map(a=>`<button class="card statline" data-action="inspect" data-id="${a.id}"><span><b>${esc(a.name)}</b><br><span class="tiny muted">${esc(a.injury||'Injured')} • ${a.recovery} day(s)</span></span><span>${a.hp}/${derived(a).maxHp} HP</span></button>`).join('')}</div>`:''}
<div class="sectionTitle"><h3>Headquarters</h3><span>Every upgrade is mechanical</span></div><div class="grid2">${Object.entries(HQ_DEFS).map(([k,x])=>{const lv=r.hq.upgrades[k]||0,cost=hqUpgradeCost(k);return`<div class="card"><div class="statline"><b>${x.icon} ${k}</b><span class="gold">${lv}/${x.max}</span></div><div class="tiny muted">${esc(x.desc)}</div><div class="actions"><button class="btn ghost" data-action="hqinfo" data-key="${esc(k)}">ⓘ</button><button class="btn ${lv<x.max&&state.company.silver>=cost?'goldbtn':''}" data-action="upgrade" data-key="${esc(k)}" ${lv>=x.max||state.company.silver<cost?'disabled':''}>${lv>=x.max?'MAX':`Upgrade ${money(cost)}`}</button></div></div>`}).join('')}</div>
<div class="sectionTitle"><h3>Active Expeditions</h3><span>${active.length}</span></div>${active.length?active.map(expeditionCard).join(''):'<div class="empty">No parties in the field.</div>'}
