
function hqUpgradeCost(k,id=state.currentRegion){const lv=hq(id).upgrades[k]||0;return Math.round(HQ_DEFS[k].base*(1+lv*.8)*(1+(100-state.regions[id].prosperity)/250))}
function upgradeHQ(k){const def=HQ_DEFS[k],r=region(),lv=r.hq.upgrades[k]||0;if(!def||lv>=def.max)return toast(`${k} is already at maximum.`);const cost=hqUpgradeCost(k);if(state.company.silver<cost)return toast(`Need ${money(cost)}.`);state.company.silver-=cost;r.hq.upgrades[k]++;pushHistory(`${k} upgraded to Level ${lv+1}.`);sfx('upgrade');save();render()}
function branchRequirements(id){const d=REGION_DEFS[id];if(id==='veyric')return{ok:true,cost:0,renown:0};if(id==='firmament'){const four=['veyric','skeld','hoshin','nambara'].every(x=>hq(x).established);return{ok:four&&state.company.silver>=d.foundCost&&state.company.renown>=d.renown,cost:d.foundCost,renown:d.renown,extra:'Requires HQs in all four mortal regions.'}}return{ok:state.company.silver>=d.foundCost&&state.company.renown>=d.renown,cost:d.foundCost,renown:d.renown}}
function foundBranch(id){const d=REGION_DEFS[id],r=state.regions[id],req=branchRequirements(id);if(r.hq.established)return switchRegion(id);if(!req.ok)return toast(`Need ${money(req.cost)} and ${req.renown} Renown${req.extra?' plus all four mortal HQs':''}.`);state.company.silver-=req.cost;r.hq.established=true;state.parties.push(makeParty(id,`${d.culture} First Company`));refreshRegion(id,true);pushHistory(`${state.company.name} established ${d.hqName}.`,id);state.currentRegion=id;state.ui.tab='hq';sfx('success');save();render()}
function switchRegion(id){if(!hq(id).established)return toast('Establish an HQ here first.');state.currentRegion=id;state.ui.tab='hq';save();render()}

function partyMembers(p){return p.members.map(id=>state.roster.find(a=>a.id===id)).filter(a=>a&&a.status!=='Dead')}
function bestUtility(p,key){let best=null;partyMembers(p).forEach(a=>{const value=derived(a).util[key];if(!best||value>best.value)best={a,value}});return best||{a:null,value:0}}
function partyProfile(p){const ms=partyMembers(p);const out={attack:0,guard:0,speed:0,accuracy:0,resolve:0};ms.forEach(a=>{const c=derived(a).combat;Object.keys(out).forEach(k=>out[k]+=c[k])});if(ms.length){out.speed/=ms.length;out.accuracy/=ms.length;out.resolve/=ms.length}const n=ms.filter(a=>a.culture==='Nambaran').length;if(n>1)out.attack*=1+(n-1)*.05;const captain=ms.find(a=>a.id===p.captainId);if(captain){const cd=derived(captain);out.resolve+=Math.min(4,Math.round(cd.combat.resolve*.08));out.attack*=1+Math.min(.08,p.cohesion/1250);out.guard*=1+Math.min(.08,p.cohesion/1250)}return out}
function createParty(){if(localParties().length>=8)return toast('This HQ cannot coordinate more parties yet.');if(state.company.silver<25)return toast('Need 25 silver to charter another party.');const name=`${regionDef().culture} Company ${localParties().length+1}`;state.parties.push(makeParty(state.currentRegion,name));state.company.silver-=25;save();render()}
function setTactic(pid,t){const p=state.parties.find(x=>x.id===pid);if(!p||p.expedition)return;p.tactic=t;save();sfx('tap');render()}
function setCaptain(pid,id){const p=state.parties.find(x=>x.id===pid);if(!p||!p.members.includes(id))return;p.captainId=id;save();render()}
function togglePartyMember(pid,aid){const p=state.parties.find(x=>x.id===pid),a=state.roster.find(x=>x.id===aid);if(!p||!a||p.expedition||a.status!=='Ready'||a.regionId!==p.regionId)return;const other=state.parties.some(q=>q.id!==p.id&&q.members.includes(aid));if(other)return toast('Already assigned to another party.');const i=p.members.indexOf(aid);if(i>=0){p.members.splice(i,1);if(p.captainId===aid)p.captainId=null}else{if(p.members.length>=partyCap(p.regionId))return toast('Party is at its current capacity.');p.members.push(aid);if(!p.captainId)p.captainId=aid}save();renderModalParty(pid)}

function hireRecruit(id){const r=region(),a=r.recruits.find(x=>x.id===id);if(!a)return;const local=localRoster();if(local.length>=rosterCap())return toast('Barracks are full.');const cost=Math.max(6,a.wage*3);if(state.company.silver<cost)return toast(`Need ${money(cost)}.`);state.company.silver-=cost;r.recruits=r.recruits.filter(x=>x.id!==id);state.roster.push(a);pushHistory(`Hired ${a.name}, ${a.culture} ${a.className}.`);sfx('hire');save();render()}
function dismissAdventurer(id){const a=state.roster.find(x=>x.id===id);if(!a||a.status==='Dead')return;state.parties.forEach(p=>p.members=p.members.filter(x=>x!==id));a.status='Dismissed';state.roster=state.roster.filter(x=>x.id!==id);pushHistory(`${a.name} left the company.`,a.regionId);save();closeModal();render()}

function buyMarket(stockId){const r=region(),s=r.market.stock.find(x=>x.id===stockId);if(!s)return;if(state.company.silver<s.price)return toast('Not enough silver.');state.company.silver-=s.price;inventoryEntry(s.item,state.currentRegion,1);r.market.stock=r.market.stock.filter(x=>x.id!==stockId);sfx('coin');save();renderMarket()}
function sellInventory(itemId){const entry=localInventory().find(x=>x.item.id===itemId);if(!entry)return;const value=Math.max(1,Math.round(itemPrice(entry.item,state.currentRegion)*.45));removeInventoryItem(itemId,state.currentRegion);state.company.silver+=value;sfx('coin');save();renderVault()}
