<div class="sectionTitle"><h3>Regional Ledger</h3><span>${r.log.length} entries</span></div><div class="card history">${r.log.slice(-14).reverse().map(x=>`<div>${esc(x)}</div>`).join('')||'<div>No history yet.</div>'}</div>`}

function rosterCard(a){const d=derived(a);return`<button class="card member" data-action="inspect" data-id="${a.id}"><div class="portrait">${RACE_ICONS[a.race]||'?'}</div><div style="text-align:left"><div class="statline"><h4>${esc(a.name)}</h4><span>Lv.${a.lvl}</span></div><div class="small muted">${esc(a.race)} • <b class="gold">${esc(a.culture)} ${esc(a.className)}</b></div><div class="tiny muted">${esc(a.background)} • ${esc(a.status)}</div><div class="hpbar"><i style="width:${clamp(a.hp/d.maxHp*100,0,100)}%"></i></div><div class="tags">${(a.traits||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><span class="tiny">›</span></button>`}
function recruitCard(a){return`<div class="card member"><div class="portrait">${RACE_ICONS[a.race]||'?'}</div><div><h4>${esc(a.name)}</h4><div class="small muted">Lv.${a.lvl} ${esc(a.race)} • <b class="gold">${esc(a.culture)} ${esc(a.className)}</b></div><div class="tiny muted">${esc(a.background)} • ${a.wage}s/week</div><div class="tags">${a.traits.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div><button class="btn ghost" data-action="inspectRecruit" data-id="${a.id}">ⓘ</button><button class="btn goldbtn" data-action="hire" data-id="${a.id}">Hire ${a.wage*3}s</button></div></div>`}
function renderRoster(){const r=region(),locals=localRoster();return`<div class="hero"><div class="kicker">${esc(REGION_DEFS[state.currentRegion].culture.toUpperCase())} RECRUITMENT</div><h2>${locals.length} adventurers stationed here</h2><p>Race, culture, class, background, traits, gear, level and relationships all contribute independently.</p></div>
<div class="sectionTitle"><h3>Your People</h3><span>${locals.length}/${rosterCap()} local capacity</span></div><div class="list">${locals.length?locals.map(rosterCard).join(''):'<div class="empty">No adventurers stationed here.</div>'}</div>
<div class="sectionTitle"><h3>Recruit Pool</h3><span>Stability ${Math.round(r.stability)} • ${stabilityText(r.stability)}</span></div><div class="list">${r.recruits.map(recruitCard).join('')}</div>
<div class="sectionTitle"><h3>Parties</h3><button class="btn ghost" data-action="newParty">+ Party</button></div>${localParties().map(partyCard).join('')}`}
function partyCard(p){const ms=partyMembers(p),cap=partyCap(p.regionId),captain=state.roster.find(a=>a.id===p.captainId);return`<div class="card partyCard"><div class="statline"><div><b>${esc(p.name)}</b><div class="tiny muted">${captain?`Captain ${esc(captain.name)} • `:''}${p.missions} missions • ${p.wins} wins${p.specialty?` • ${esc(p.specialty)}`:''}</div></div><span>${ms.length}/${cap}</span></div><div class="faces">${ms.map(a=>`<div class="face" title="${esc(a.name)}">${RACE_ICONS[a.race]}<small>${a.lvl}</small></div>`).join('')||'<span class="small muted">Empty party</span>'}</div><div class="cohesion">Cohesion ${p.cohesion}/100</div><div class="tactics">${['Cautious','Balanced','Aggressive'].map(t=>`<button class="tactic ${p.tactic===t?'active':''}" data-action="tactic" data-id="${p.id}" data-value="${t}" ${p.expedition?'disabled':''}>${t}</button>`).join('')}</div><div class="actions"><button class="btn" data-action="editParty" data-id="${p.id}" ${p.expedition?'disabled':''}>Assign Members</button>${p.expedition?`<button class="btn primary" data-action="nav" data-tab="contracts">Monitor</button>`:''}</div></div>`}

function contractCard(c){const r=state.regions[c.regionId],nem=c.nemesisId?state.nemeses.find(n=>n.id===c.nemesisId&&n.alive):null;return`<div class="card contract ${nem?'boss':''}"><div class="statline"><h4>${esc(c.title)}</h4><span class="riskDots">${'●'.repeat(c.risk)}${'○'.repeat(5-c.risk)}</span></div><div class="small muted">${esc(c.type)} • ${esc(c.species)} • approximately ${c.enemyCount} enemies</div><p class="small">${esc(c.desc)}</p><div class="grid3"><div class="tiny"><span class="muted">Reward</span><br><b class="gold">${money(c.reward)}</b></div><div class="tiny"><span class="muted">Field check</span><br>${esc(c.check)}</div><div class="tiny"><span class="muted">Unknowns</span><br>${c.unknown}</div></div>${nem?`<div class="notice danger"><b>Named enemy:</b> ${esc(nem.name)} • Level ${nem.level}</div>`:''}<div class="actions"><button class="btn ghost" data-action="contractInfo" data-id="${c.id}">Inspect</button><button class="btn primary" data-action="chooseParty" data-id="${c.id}">Send Party</button></div></div>`}
function renderContracts(){const r=region(),active=localParties().filter(p=>p.expedition);return`<div class="hero"><div class="kicker">THREAT ${Math.round(r.threat)} • ${threatText(r.threat).toUpperCase()}</div><h2>${r.contracts.length} contracts on the board</h2><p>Threat controls the risk distribution, enemy count, elites and named enemy activity.</p></div><div class="sectionTitle"><h3>Available Work</h3><span>Risk scales from 1–5</span></div><div class="list">${r.contracts.map(contractCard).join('')}</div><div class="sectionTitle"><h3>In the Field</h3><span>${active.length}</span></div>${active.length?active.map(expeditionCard).join(''):'<div class="empty">No active expeditions.</div>'}`}
function expeditionCard(p){const e=p.expedition;if(!e)return'';return`<div class="card"><div class="statline"><b>${esc(p.name)}</b><span class="gold">${esc(e.contract.title)}</span></div><div class="bar goldbar"><i style="width:${e.progress}%"></i></div><div class="tiny muted">${e.progress}% complete • ${esc(e.contract.species)} opposition</div>${e.battle?battleHTML(e.battle):''}<div class="combatLog">${(e.battle?e.battle.log:e.events).slice(-14).map(x=>`<div>${esc(x)}</div>`).join('')}</div><div class="actions"><button class="btn primary" data-action="advance" data-id="${p.id}">${e.battle?'Resolve Round':'Push Expedition'}</button></div></div>`}
function battleHTML(b){return`<div class="battleGrid"><div><div class="tiny gold">YOUR LINE</div><div class="unitList">${b.allies.map(u=>unitHTML(u)).join('')}</div></div><div><div class="tiny danger">ENEMY LINE</div><div class="unitList">${b.enemies.map(u=>unitHTML(u)).join('')}</div></div></div>`}
function unitHTML(u){return`<div class="unit ${u.hp<=0?'dead':''}"><div class="unitTop"><b>${esc(u.name)}</b><span>${Math.max(0,Math.round(u.hp))}/${u.maxHp}</span></div><div class="hpbar"><i style="width:${clamp(u.hp/u.maxHp*100,0,100)}%"></i></div></div>`}

function renderWorld(){return`<div class="hero"><div class="kicker">COMPANY NETWORK</div><h2>Five regions. One company.</h2><p>Prosperity drives markets. Stability drives recruitment. Threat drives contract danger and territorial loss.</p></div><div class="list">${REGION_ORDER.map(regionCard).join('')}</div>`}
function regionCard(id){const r=state.regions[id],d=REGION_DEFS[id],req=branchRequirements(id),current=id===state.currentRegion;return`<div class="card regionCard ${current?'regionCurrent':''} ${r.lost?'lost':''}"><div class="regionHead"><div><h3>${d.culture==='Aethren'?'✧':CULTURES[d.culture].icon} ${esc(d.name)}</h3><div class="tiny muted">${esc(d.culture)} culture • Common threat: <b>${esc(d.common)}</b></div></div><span class="pill">${r.hq.established?'HQ ACTIVE':'NO HQ'}</span></div><p class="small muted">${esc(d.desc)}</p><div class="regionStats"><div class="regionStat"><span>PROSPERITY</span><b>${Math.round(r.prosperity)}</b><div class="meter"><i style="width:${r.prosperity}%"></i></div></div><div class="regionStat"><span>STABILITY</span><b>${Math.round(r.stability)}</b><div class="meter"><i style="width:${r.stability}%"></i></div></div><div class="regionStat"><span>THREAT</span><b>${Math.round(r.threat)}</b><div class="meter"><i style="width:${r.threat}%"></i></div></div></div><div class="stockMeta"><span class="tag">Market: ${marketQualityText(r.prosperity)}</span><span class="tag">Recruitment: ${stabilityText(r.stability)}</span><span class="tag">Settlements ${r.settlements}/${r.totalSettlements}</span><span class="tag">Nemeses ${state.nemeses.filter(n=>n.regionId===id&&n.alive).length}</span></div><div class="actions">${r.hq.established?`<button class="btn ${current?'':'primary'}" data-action="switchRegion" data-id="${id}" ${current?'disabled':''}>${current?'Current HQ':'Switch HQ'}</button>`:`<button class="btn goldbtn" data-action="foundBranch" data-id="${id}">Found Branch • ${money(req.cost)} • ${req.renown} Renown</button>`}<button class="btn ghost" data-action="regionInfo" data-id="${id}">Details</button></div></div>`}

function itemHTML(item){return`<div class="card itemCard"><div class="statline"><div><b class="rarity-${item.rarity+1}">${esc(RARITIES[item.rarity]||'Legacy')} ${esc(item.name)}</b><div class="tiny muted">${esc(item.slot||item.type||'item')} • ${item.mods?.length||0} modifier${item.mods?.length===1?'':'s'}</div></div><span class="rarity-${item.rarity+1}">${item.rarity+1}◆</span></div><div class="itemMods">${(item.mods||[]).map(m=>`<div>• ${esc(m.label)}</div>`).join('')||'<div>• Legacy item with no generated modifiers.</div>'}</div></div>`}