function audioCtx(){if(audio?.ctx)return audio.ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;const ctx=new AC(),musicGain=ctx.createGain(),sfxGain=ctx.createGain();musicGain.connect(ctx.destination);sfxGain.connect(ctx.destination);audio={ctx,musicGain,sfxGain,musicNodes:[],musicTimer:null,unlocked:false};updateAudioGains();return ctx}
function updateAudioGains(){if(!audio||!state)return;audio.sfxGain.gain.value=.18*(state.settings.sfxVolume??.9);audio.musicGain.gain.value=.11*(state.settings.musicVolume??.8)}
function updateMusicVolume(){updateAudioGains()}
function unlockAudio(){if(!state)return;const ctx=audioCtx();if(!ctx)return;if(audio.unlocked&&ctx.state==='running')return;const finish=()=>{audio.unlocked=true;updateAudioGains();if(state.settings.sfx)simpleTone(520,.08,'triangle',.22,true);if(state.settings.music)startMusic()};if(ctx.state==='suspended')ctx.resume().then(finish).catch(()=>{});else finish()}
function simpleTone(freq,dur=.08,type='sine',gain=.18,force=false,delay=0){if(!state||(!force&&!state.settings.sfx))return;const ctx=audioCtx();if(!ctx||ctx.state!=='running')return;const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audio.sfxGain);o.start(t);o.stop(t+dur+.02)}
function noise(dur=.06,gain=.14){if(!state?.settings.sfx)return;const ctx=audioCtx();if(!ctx||ctx.state!=='running')return;const len=Math.floor(ctx.sampleRate*dur),buf=ctx.createBuffer(1,len,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=buf;g.gain.value=gain;src.connect(g);g.connect(audio.sfxGain);src.start()}
function sfx(name,force=false){if(!state||(!force&&!state.settings.sfx))return;switch(name){case'tap':simpleTone(170,.045,'triangle',.12,force);break;case'hire':simpleTone(390,.07,'triangle',.18,force);simpleTone(620,.09,'triangle',.16,force,.06);break;case'coin':simpleTone(720,.05,'sine',.17,force);simpleTone(960,.07,'sine',.14,force,.05);break;case'depart':simpleTone(180,.1,'sawtooth',.12,force);simpleTone(240,.14,'triangle',.1,force,.08);break;case'hit':noise(.05,.12);simpleTone(90,.06,'square',.1,force);break;case'danger':simpleTone(120,.14,'sawtooth',.14,force);simpleTone(95,.18,'sawtooth',.12,force,.12);break;case'loot':simpleTone(430,.07,'sine',.16,force);simpleTone(650,.08,'sine',.15,force,.06);simpleTone(870,.11,'sine',.13,force,.13);break;case'success':simpleTone(330,.09,'triangle',.18,force);simpleTone(495,.11,'triangle',.17,force,.07);simpleTone(660,.15,'triangle',.15,force,.14);break;case'fail':simpleTone(180,.14,'sawtooth',.16,force);simpleTone(110,.2,'triangle',.14,force,.12);break;case'upgrade':simpleTone(300,.06,'triangle',.15,force);simpleTone(450,.08,'triangle',.16,force,.05);simpleTone(600,.1,'triangle',.16,force,.11);break;case'level':simpleTone(440,.06,'sine',.16,force);simpleTone(660,.08,'sine',.16,force,.06);simpleTone(880,.12,'sine',.16,force,.13);break;case'rest':simpleTone(260,.12,'sine',.11,force);simpleTone(195,.16,'sine',.1,force,.1);break}}
function startMusic(){if(!state?.settings.music)return;const ctx=audioCtx();if(!ctx||ctx.state!=='running'||audio.musicTimer)return;updateAudioGains();const pulse=()=>{if(!state?.settings.music||ctx.state!=='running')return;const roots=[110,123.47,98,130.81],root=pick(roots),now=ctx.currentTime;[1,1.5,2].forEach((mult,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===0?'sine':'triangle';o.frequency.value=root*mult;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(i===0?.18:.05,now+.6);g.gain.exponentialRampToValueAtTime(.0001,now+5.4);o.connect(g);g.connect(audio.musicGain);o.start(now);o.stop(now+5.5);audio.musicNodes.push(o)});audio.musicNodes=audio.musicNodes.filter(n=>true)};pulse();audio.musicTimer=setInterval(pulse,5200)}
function stopMusic(){if(!audio)return;if(audio.musicTimer){clearInterval(audio.musicTimer);audio.musicTimer=null}audio.musicNodes.forEach(n=>{try{n.stop()}catch(e){}});audio.musicNodes=[]}

function audit(){const out={version:VERSION,regionCount:REGION_ORDER.length};const test=createState('Audit Company');return withState(test,()=>{out.rarityModifierCounts=[0,1,2,3,4].map(r=>generateItem('veyric',r).mods.length);out.rarityOK=out.rarityModifierCounts.every((n,i)=>n===i+1);out.hasFiveRegions=REGION_ORDER.length===5;out.upgradesMechanical=Object.keys(HQ_DEFS).every(k=>typeof HQ_DEFS[k].desc==='string'&&HQ_DEFS[k].max>0);const baseRoster=rosterCap('veyric'),baseParty=partyCap('veyric');hq('veyric').upgrades.Barracks++;hq('veyric').upgrades['Command Hall']++;out.barracksChangesCapacity=rosterCap('veyric')>baseRoster;out.commandHallChangesPartyCap=partyCap('veyric')>baseParty;const rr=state.regions.veyric;rr.prosperity=20;refreshMarket('veyric',true);const lowPrice=rr.market.stock.reduce((s,x)=>s+x.price,0)/rr.market.stock.length,lowStock=rr.market.stock.length;rr.prosperity=90;refreshMarket('veyric',true);const highPrice=rr.market.stock.reduce((s,x)=>s+x.price,0)/rr.market.stock.length,highStock=rr.market.stock.length;out.prosperityChangesMarket=highStock>lowStock&&highPrice>0&&lowPrice>0;rr.stability=20;refreshRecruits('veyric');const lowRecruits=rr.recruits.length;rr.stability=90;refreshRecruits('veyric');out.stabilityChangesRecruitment=rr.recruits.length>lowRecruits;rr.threat=15;const lowRisk=Array.from({length:80},()=>contractRisk('veyric')).reduce((a,b)=>a+b,0)/80;rr.threat=95;const highRisk=Array.from({length:80},()=>contractRisk('veyric')).reduce((a,b)=>a+b,0)/80;out.threatChangesRisk=highRisk>lowRisk+2;out.newGameNamingRequired=!createState('').company.name;out.tacticsMechanical=/Cautious/.test(allyAttack.toString())&&/Aggressive/.test(enemyAttack.toString());out.enemyTypesMechanical=/Goblin/.test(startBattle.toString())&&/regen/.test(combatRound.toString())&&/horror/.test(startBattle.toString());return out})}
window.__BL_AUDIT=audit;

async function boot(){state=await loadState();if(state){REGION_ORDER.forEach(id=>refreshRegion(id,false));save();render()}else renderStart();if(autoTimer)clearInterval(autoTimer);autoTimer=setInterval(()=>{if(!state||document.hidden)return;state.parties.filter(x=>x.expedition).forEach(p=>advanceExpedition(p.id,false))},1700)}

document.addEventListener('pointerdown',()=>{if(state)unlockAudio()},{once:false,passive:true});
boot();
})();
