function showGear(aid){const a=state.roster.find(x=>x.id===aid);if(!a)return;const inv=state.inventory.filter(x=>x.regionId===a.regionId&&['weapon','armor','charm'].includes(x.item.slot));modal(`<div class="sheetHead"><h3>Equipment • ${esc(a.name)}</h3><button class="x" data-action="close">✕</button></div>${['weapon','armor','charm'].map(slot=>`<div class="sectionTitle"><h3>${slot.toUpperCase()}</h3>${a.gear[slot]?`<button class="btn ghost" data-action="unequip" data-id="${a.id}" data-slot="${slot}">Unequip</button>`:''}</div>${a.gear[slot]?itemHTML(a.gear[slot]):'<div class="empty">Empty slot</div>'}<div class="list">${inv.filter(e=>e.item.slot===slot).map(e=>`<button class="card" data-action="equip" data-id="${a.id}" data-item="${e.item.id}" style="text-align:left"><b class="rarity-${e.item.rarity+1}">${esc(RARITIES[e.item.rarity])} ${esc(e.item.name)}</b><div class="tiny muted">${e.item.mods.map(m=>esc(m.label)).join(' • ')}</div></button>`).join('')}</div>`).join('')}`)}
function showItemInfo(itemId){let item=null;for(const e of state.inventory)if(e.item.id===itemId)item=e.item;if(!item)for(const r of Object.values(state.regions)){const s=r.market.stock.find(x=>x.item.id===itemId);if(s)item=s.item}if(item)modal(`<div class="sheetHead"><h3>Item</h3><button class="x" data-action="close">✕</button></div>${itemHTML(item)}<div class="notice">Rarity determines both modifier count and modifier magnitude.</div>`)}
function infoRace(name){const r=RACES[name];if(r)modal(`<div class="sheetHead"><h3>${esc(name)} • Race</h3><button class="x" data-action="close">✕</button></div><div class="card"><b>${esc(r.passive)}</b><p class="small muted">${esc(r.desc)}</p></div>`)}
function infoCulture(name){const c=CULTURES[name];if(c)modal(`<div class="sheetHead"><h3>${esc(name)} • Culture</h3><button class="x" data-action="close">✕</button></div><div class="card"><b>${esc(c.passive)}</b><p class="small muted">${esc(c.desc)}</p><div class="tiny gold">Homeland: ${esc(c.homeland)}</div></div>`)}
function infoClass(aid,recruit){const a=(recruit?region().recruits:state.roster).find(x=>x.id===aid);if(!a)return;const c=classRule(a);modal(`<div class="sheetHead"><h3>${esc(c.name)} • Class</h3><button class="x" data-action="close">✕</button></div><div class="card"><b>${esc(c.role)}</b><p class="small muted">${esc(c.desc)}</p><div class="gold small">${esc(c.ability)}</div></div>`)}
function traitInfo(name){modal(`<div class="sheetHead"><h3>${esc(name)}</h3><button class="x" data-action="close">✕</button></div><div class="card small">${esc(traitDesc(name))}</div>`)}

function restDay(){if(state.parties.some(p=>p.expedition))return toast('Resolve active expeditions before standing the company down.');advanceDay('The company stood down for repairs, training and recovery.');sfx('rest');render();toast('One game day passed.')}
function buyAction(id){buyMarket(id)}
function startCompany(){const input=document.getElementById('companyName');const name=(input?.value||'').trim();if(name.length<2)return toast('Give the company a name first.');state=createState(name);safeLocalRemove(LEGACY_KEY);save();unlockAudio();render();toast(`${name} founded in Greyhaven.`)}

function processAction(el){const a=el.dataset.action;if(!a)return;unlockAudio();switch(a){
 case'begin':return startCompany();case'nav':state.ui.tab=el.dataset.tab;save();return render();case'menu':return showMenu();case'audio':return showAudio();case'close':return closeModal();case'market':return renderMarket();case'rest':return restDay();case'facilities':return showFacilities();case'hqinfo':return hqInfo(el.dataset.key);case'upgrade':return upgradeHQ(el.dataset.key);case'inspect':return renderInspect(el.dataset.id,false);case'inspectRecruit':return renderInspect(el.dataset.id,true);case'hire':return hireRecruit(el.dataset.id);case'newParty':return createParty();case'editParty':return renderModalParty(el.dataset.id);case'toggleMember':return togglePartyMember(el.dataset.party,el.dataset.id);case'captain':return setCaptain(el.dataset.party,el.dataset.id),renderModalParty(el.dataset.party);case'tactic':return setTactic(el.dataset.id,el.dataset.value);case'contractInfo':return showContractInfo(el.dataset.id);case'chooseParty':return showChooseParty(el.dataset.id);case'dispatch':return dispatchContract(el.dataset.id,el.dataset.party);case'advance':return advanceExpedition(el.dataset.id,true);case'switchRegion':return switchRegion(el.dataset.id);case'foundBranch':return foundBranch(el.dataset.id);case'regionInfo':return showRegionInfo(el.dataset.id);case'openCache':return openCache(el.dataset.id);case'sell':return sellInventory(el.dataset.id);case'itemInfo':return showItemInfo(el.dataset.id);case'buy':return buyAction(el.dataset.id);case'gear':return showGear(el.dataset.id);case'equip':return equipItem(el.dataset.id,el.dataset.item);case'unequip':return unequip(el.dataset.id,el.dataset.slot);case'infoRace':return infoRace(el.dataset.id);case'infoCulture':return infoCulture(el.dataset.id);case'infoClass':return infoClass(el.dataset.id,el.dataset.recruit==='1');case'traitInfo':return traitInfo(el.dataset.id);case'backup':return showBackup();case'forceSave':save();return toast('Company saved.');case'copySave':return copyBackup();case'restoreSave':return restoreBackup();case'newGame':return beginNewGame();case'newGameConfirm':return hardNewGame();case'toggleSfx':state.settings.sfx=!state.settings.sfx;save();return showAudio();case'toggleMusic':state.settings.music=!state.settings.music;save();if(state.settings.music)startMusic();else stopMusic();return showAudio();case'testSound':sfx('success',true);return;}}

document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)processAction(el)});
document.addEventListener('input',e=>{if(!state)return;if(e.target.dataset.range==='sfx'){state.settings.sfxVolume=Number(e.target.value)/100;save()}if(e.target.dataset.range==='music'){state.settings.musicVolume=Number(e.target.value)/100;save();updateMusicVolume()}});
document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
async function copyBackup(){try{await navigator.clipboard.writeText(JSON.stringify(state));toast('Backup copied.')}catch(e){toast('Clipboard unavailable on this browser.')}}
function restoreBackup(){const t=document.getElementById('restoreBox');try{const next=normalizeState(JSON.parse(t.value.trim()));if(!next)throw 0;state=next;save();closeModal();render();toast('Backup restored.')}catch(e){toast('That backup is invalid.')}}

