from pathlib import Path
import re

p=Path('archive-demo/index.html')
text=p.read_text(encoding='utf-8')

if 'Atmosphere Build · v7' in text:
    print('v7 already applied')
    raise SystemExit(0)

def rep(old,new,count=1):
    global text
    n=text.count(old)
    if n < count:
        raise SystemExit(f'missing marker: {old[:90]!r} (found {n})')
    text=text.replace(old,new,count)

rep('<title>Sovereign Archive — Living Archive</title>','<title>Sovereign Archive — Atmosphere Build</title>')

css=r'''
/* v7 atmosphere + audio */
body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:200;opacity:.055;background-image:radial-gradient(circle at 20% 30%,#fff 0 1px,transparent 1.5px),radial-gradient(circle at 80% 65%,#fff 0 .7px,transparent 1.2px);background-size:73px 61px,91px 83px;mix-blend-mode:soft-light}.scene{isolation:isolate;transform:translateZ(0)}.scene svg{animation:sceneDrift 12s ease-in-out infinite alternate;transform-origin:50% 60%}.sceneShade{z-index:2}.sceneText{z-index:3;text-shadow:0 2px 16px rgba(0,0,0,.72)}.scene:after{content:"";position:absolute;inset:-25%;z-index:1;pointer-events:none}.gothamGlow .scene:after{opacity:.24;background:repeating-linear-gradient(112deg,transparent 0 18px,rgba(167,205,255,.42) 19px,transparent 21px 38px);animation:gothamRain .7s linear infinite}.metroGlow .scene:after{inset:-10%;opacity:.18;background:radial-gradient(circle at 78% 8%,rgba(255,244,181,.95),transparent 15%),linear-gradient(115deg,transparent 28%,rgba(255,255,255,.28) 47%,transparent 65%);animation:metroGlow 7s ease-in-out infinite alternate}.archiveGlow .scene:after{opacity:.22;background:radial-gradient(circle at 50% 44%,transparent 0 16%,rgba(177,151,255,.24) 20%,transparent 28%),conic-gradient(from 0deg at 50% 44%,transparent,rgba(209,175,112,.13),transparent 22%,rgba(128,103,255,.13),transparent 47%);animation:archivePulse 9s linear infinite}.archiveTheme-neon .scene:after{filter:hue-rotate(70deg) saturate(1.25)}.archiveTheme-gallery .scene:after{filter:hue-rotate(-25deg) saturate(.9)}
@keyframes sceneDrift{to{transform:scale(1.018) translate3d(0,-1px,0)}}@keyframes gothamRain{to{transform:translate3d(-18px,38px,0)}}@keyframes metroGlow{to{opacity:.3;transform:translate3d(-2%,1%,0) scale(1.03)}}@keyframes archivePulse{to{transform:rotate(360deg) scale(1.02)}}
.choice,.operation,.decision,.btn,.miniBtn,.tacticBtn,.navBtn{transition:transform .12s ease,border-color .18s ease,background .18s ease,box-shadow .18s ease}.choice:active,.operation:active,.decision:active,.miniBtn:active{transform:scale(.985)}.choice:not(.locked):hover,.operation:hover,.decision:not(:disabled):hover{border-color:rgba(255,255,255,.19)}.btn.primary,.miniBtn.active{box-shadow:inset 0 1px rgba(255,255,255,.06),0 0 24px rgba(209,175,112,.05)}.situationCard{box-shadow:0 15px 55px rgba(0,0,0,.18),inset 0 1px rgba(255,255,255,.035)}.roomCard{overflow:hidden}.roomCard:after{content:"";position:absolute;width:90px;height:90px;right:-42px;bottom:-52px;border:1px solid color-mix(in srgb,var(--accent) 26%,transparent);border-radius:50%;box-shadow:0 0 30px color-mix(in srgb,var(--accent) 10%,transparent)}
.battleShell{position:relative;overflow:hidden;isolation:isolate}.battleShell>*{position:relative;z-index:2}.battleShell:before{content:"";position:absolute;inset:-40%;z-index:0;pointer-events:none;background:conic-gradient(from 90deg,transparent,rgba(128,103,255,.07),transparent 22%,rgba(209,175,112,.05),transparent 52%);animation:battleAtmos 13s linear infinite}.gothamGlow .battleShell{background:radial-gradient(560px 300px at 100% 0%,rgba(80,124,190,.17),transparent 60%),linear-gradient(180deg,#111929,#080d16)}.metroGlow .battleShell{background:radial-gradient(600px 280px at 90% -10%,rgba(255,224,142,.13),transparent 58%),linear-gradient(180deg,#17233a,#0b111d)}@keyframes battleAtmos{to{transform:rotate(360deg)}}.unit.hero{background:linear-gradient(145deg,rgba(209,175,112,.055),rgba(0,0,0,.17))}.unit.enemy{background:linear-gradient(145deg,rgba(255,105,123,.045),rgba(0,0,0,.17))}.unit.dead{transform:translateY(3px)}.combatSprite.attack:after{content:"";position:absolute;left:28px;top:19px;width:32px;height:3px;border-radius:50%;background:linear-gradient(90deg,var(--s2),transparent);filter:drop-shadow(0 0 4px var(--s2));animation:attackTrail .34s ease}.combatSprite.hit:before{content:"";position:absolute;inset:-8px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.55),transparent 65%);animation:hitFlash .34s ease;z-index:-1}@keyframes attackTrail{from{opacity:0;transform:scaleX(.2)}40%{opacity:1}to{opacity:0;transform:translateX(12px) scaleX(1.15)}}@keyframes hitFlash{from{opacity:0}35%{opacity:1}to{opacity:0}}
.soundDock{position:fixed;z-index:70;right:12px;top:calc(58px + env(safe-area-inset-top));border:1px solid rgba(255,255,255,.13);background:rgba(12,16,26,.88);backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(0,0,0,.32);border-radius:999px;min-width:42px;height:42px;padding:0 12px;color:#f0f2f7;font-size:10px;font-weight:900;letter-spacing:.03em}.soundDock.on{min-width:42px;width:42px;padding:0;color:var(--accent);border-color:color-mix(in srgb,var(--accent) 32%,transparent)}.soundDock .pulse{display:inline-block;width:6px;height:6px;margin-right:6px;border-radius:50%;background:var(--accent);box-shadow:0 0 12px var(--accent);animation:soundPulse 1.8s ease-in-out infinite}.soundDock.on .pulse{margin:0}@keyframes soundPulse{50%{opacity:.35;transform:scale(.75)}}.audioStatus{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:10px 0}.audioTile{padding:10px;border-radius:14px;border:1px solid var(--line);background:rgba(255,255,255,.035);text-align:center}.audioTile b{display:block;font-size:13px}.audioTile span{display:block;margin-top:3px;font-size:8px;color:var(--muted);text-transform:uppercase}.volumeRow{display:grid;grid-template-columns:80px 1fr 34px;gap:9px;align-items:center;margin-top:11px}.volumeRow label{font-size:9px;font-weight:850;color:var(--muted);text-transform:uppercase}.volumeRow input{width:100%;accent-color:var(--accent)}.volumeRow output{font-size:9px;color:var(--accent);text-align:right}.audioHint{padding:10px 11px;border-left:2px solid var(--accent);background:rgba(255,255,255,.035);border-radius:3px 11px 11px 3px;color:var(--muted);font-size:9px;line-height:1.45;margin-top:11px}
@media(max-width:520px){.soundDock{top:calc(55px + env(safe-area-inset-top));right:9px;height:38px}.soundDock:not(.on){padding:0 10px}.sceneTitle{font-size:29px}.battleShell{border-radius:22px}.unitVisual{height:69px}}@media(prefers-reduced-motion:reduce){.scene svg,.scene:after,.battleShell:before,.combatSprite,.soundDock .pulse{animation:none!important}}
'''
rep('\n</style>', '\n'+css+'\n</style>')

rep("function defaultArchive(){return {theme:'library',upgrades:{manifest:0,armory:0,recovery:0,analysis:0,gallery:0}}}function defaultCosmetics(){return {outfit:'street',accent:'violet',hair:'dark'}}function defaultWorld(){", "function defaultArchive(){return {theme:'library',upgrades:{manifest:0,armory:0,recovery:0,analysis:0,gallery:0}}}function defaultCosmetics(){return {outfit:'street',accent:'violet',hair:'dark'}}function defaultAudio(){return {enabled:false,music:true,sfx:true,musicVol:.28,sfxVol:.52}}function defaultWorld(){")
rep("const fresh=()=>({version:6,", "const fresh=()=>({version:7,")
rep("archive:defaultArchive(),cosmetics:defaultCosmetics(),world:defaultWorld(),", "archive:defaultArchive(),cosmetics:defaultCosmetics(),audio:defaultAudio(),world:defaultWorld(),")
rep("s={...f,...s};s.version=6;", "s={...f,...s};s.version=7;")
rep("s.cosmetics={...defaultCosmetics(),...(s.cosmetics||{})};const dw=defaultWorld();", "s.cosmetics={...defaultCosmetics(),...(s.cosmetics||{})};s.audio={...defaultAudio(),...(s.audio||{})};const dw=defaultWorld();")
rep('Living Archive · v6','Atmosphere Build · v7')
rep('Sovereign Archive — Living Archive','Sovereign Archive — Atmosphere Build')

engine=r'''
const AUDIO_PATTERNS={
 archive:{ms:720,wave:'sine',lead:[220,null,277,null,330,null,277,null,196,null,247,null,294,null,247,null],bass:[110,null,null,null,98,null,null,null],gain:.055},
 gotham:{ms:610,wave:'triangle',lead:[147,null,175,165,null,147,null,131,147,null,196,null,175,null,147,null],bass:[73.4,null,null,65.4,null,null,73.4,null],gain:.05},
 metropolis:{ms:530,wave:'sine',lead:[262,330,392,null,330,392,440,null,294,370,440,null,392,330,null,null],bass:[131,null,147,null,165,null,147,null],gain:.045},
 combat:{ms:255,wave:'square',lead:[165,196,220,196,165,247,220,196,175,220,262,220,196,294,262,220],bass:[82.4,null,82.4,null,87.3,null,98,null],gain:.032}
};
let audioCtx=null,audioMaster=null,musicBus=null,sfxBus=null,musicTimer=null,musicSceneName='',musicStep=0;
function ensureAudio(){if(audioCtx)return true;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;audioCtx=new AC();audioMaster=audioCtx.createGain();musicBus=audioCtx.createGain();sfxBus=audioCtx.createGain();musicBus.connect(audioMaster);sfxBus.connect(audioMaster);audioMaster.connect(audioCtx.destination);syncAudioVolumes();return true}catch(e){return false}}
function syncAudioVolumes(){if(!audioCtx)return;audioMaster.gain.setTargetAtTime(state.audio?.enabled?1:0,audioCtx.currentTime,.02);musicBus.gain.setTargetAtTime(state.audio?.music?clamp(Number(state.audio.musicVol)||0,0,1):0,audioCtx.currentTime,.03);sfxBus.gain.setTargetAtTime(state.audio?.sfx?clamp(Number(state.audio.sfxVol)||0,0,1):0,audioCtx.currentTime,.02)}
function tone(freq,dur=.12,vol=.08,wave='sine',bus=sfxBus,delay=0){if(!audioCtx||!bus||!freq)return;const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=wave;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(bus);o.start(t);o.stop(t+dur+.025)}
function noise(dur=.08,vol=.025){if(!audioCtx||!sfxBus)return;const len=Math.max(1,Math.floor(audioCtx.sampleRate*dur)),buf=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=audioCtx.createBufferSource(),g=audioCtx.createGain();src.buffer=buf;g.gain.value=vol;src.connect(g);g.connect(sfxBus);src.start()}
function desiredMusicScene(){return state.screen==='combat'?'combat':state.city==='gotham'?'gotham':state.city==='metropolis'?'metropolis':'archive'}
function musicTick(){if(!audioCtx||!state.audio.enabled||!state.audio.music)return;const p=AUDIO_PATTERNS[musicSceneName]||AUDIO_PATTERNS.archive,lead=p.lead[musicStep%p.lead.length],bass=p.bass[musicStep%p.bass.length];if(lead)tone(lead,.28,p.gain,p.wave,musicBus);if(bass)tone(bass,.42,p.gain*.72,'sine',musicBus,.018);if(musicSceneName==='archive'&&musicStep%8===0)tone(lead?lead/2:110,.65,.018,'sine',musicBus,.08);musicStep++}
function startMusicScene(name,force=false){if(!state.audio.enabled||!state.audio.music||!audioCtx)return stopMusic();if(!force&&name===musicSceneName&&musicTimer)return;stopMusic();musicSceneName=name;musicStep=0;musicTick();musicTimer=setInterval(musicTick,(AUDIO_PATTERNS[name]||AUDIO_PATTERNS.archive).ms)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function initAudio(fromGesture=false){if(!state.audio?.enabled&&!fromGesture)return false;if(!ensureAudio())return false;const resume=audioCtx.state==='suspended'?audioCtx.resume():Promise.resolve();resume.then(()=>{syncAudioVolumes();if(state.audio.enabled&&state.audio.music)startMusicScene(desiredMusicScene(),true)}).catch(()=>{});return true}
function syncAudioScene(){if(!state.audio?.enabled)return;if(!audioCtx)return;syncAudioVolumes();startMusicScene(desiredMusicScene())}
function sfx(name){if(!state.audio?.enabled||!state.audio.sfx)return;if(!ensureAudio())return;if(audioCtx.state==='suspended'){audioCtx.resume().catch(()=>{});return}const v=.09;switch(name){case'tap':tone(520,.045,.025,'sine');break;case'portal':tone(147,.35,.05,'sine');tone(220,.42,.045,'sine',sfxBus,.08);tone(330,.5,.035,'triangle',sfxBus,.16);break;case'alert':tone(196,.11,.05,'square');tone(147,.18,.045,'square',sfxBus,.12);break;case'round':tone(110,.055,.025,'square');noise(.045,.012);break;case'claim':tone(220,.2,.06,'sine');tone(330,.26,.055,'triangle',sfxBus,.08);tone(494,.32,.04,'sine',sfxBus,.16);break;case'discover':tone(392,.11,.045,'sine');tone(523,.18,.04,'sine',sfxBus,.09);break;case'upgrade':tone(262,.12,.05,'triangle');tone(392,.16,.05,'triangle',sfxBus,.09);tone(523,.24,.045,'sine',sfxBus,.18);break;case'decision':tone(247,.09,.04,'triangle');tone(294,.14,.035,'triangle',sfxBus,.07);break;case'heal':tone(330,.12,.045,'sine');tone(440,.2,.04,'sine',sfxBus,.09);break;case'ko':noise(.13,.035);tone(82,.22,.05,'sawtooth');break;case'victory':tone(262,.13,v,'triangle');tone(330,.13,v,'triangle',sfxBus,.11);tone(392,.15,v,'triangle',sfxBus,.22);tone(523,.38,.07,'sine',sfxBus,.34);break;case'defeat':tone(196,.2,.055,'sawtooth');tone(165,.26,.05,'sawtooth',sfxBus,.16);tone(131,.4,.045,'sine',sfxBus,.34);break;case'confirm':tone(440,.1,.04,'sine');tone(660,.16,.035,'sine',sfxBus,.08);break;}}
function toggleAudio(on){state.audio.enabled=on===undefined?!state.audio.enabled:!!on;save();if(state.audio.enabled){initAudio(true);sfx('confirm')}else{syncAudioVolumes();stopMusic()}updateAudioDock()}
function updateAudioDock(){document.querySelector('.soundDock')?.remove();const b=document.createElement('button');b.className='soundDock '+(state.audio.enabled?'on':'');b.setAttribute('aria-label',state.audio.enabled?'Sound settings':'Enable sound');b.innerHTML=state.audio.enabled?'<span class="pulse"></span>':'<span class="pulse"></span> Sound On';b.onclick=()=>state.audio.enabled?soundSettingsPanel():toggleAudio(true);document.body.appendChild(b)}
function soundSettingsPanel(){const d=sheet('Sound & Atmosphere','Tiny procedural soundtrack. Nothing is streamed or downloaded.');const a=state.audio;d.querySelector('.sheet').insertAdjacentHTML('beforeend',`<div class="audioStatus"><div class="audioTile"><b>${a.enabled?'ON':'OFF'}</b><span>Master</span></div><div class="audioTile"><b>${a.music?'ON':'OFF'}</b><span>Music</span></div><div class="audioTile"><b>${a.sfx?'ON':'OFF'}</b><span>SFX</span></div></div><div class="miniBtns"><button class="miniBtn ${a.enabled?'active':''}" data-audio-master>${a.enabled?'Mute Everything':'Enable Sound'}</button><button class="miniBtn ${a.music?'active':''}" data-audio-music>Music ${a.music?'On':'Off'}</button><button class="miniBtn ${a.sfx?'active':''}" data-audio-sfx>SFX ${a.sfx?'On':'Off'}</button></div><div class="volumeRow"><label>Music</label><input type="range" min="0" max="100" value="${Math.round(a.musicVol*100)}" data-musicvol><output>${Math.round(a.musicVol*100)}</output></div><div class="volumeRow"><label>Effects</label><input type="range" min="0" max="100" value="${Math.round(a.sfxVol*100)}" data-sfxvol><output>${Math.round(a.sfxVol*100)}</output></div><div class="audioHint">iPhone browsers require one physical tap before audio can begin. Once enabled, the soundtrack follows the Archive, Gotham, Metropolis and combat automatically.</div>`);d.querySelector('[data-audio-master]').onclick=()=>{toggleAudio(!state.audio.enabled);d.remove();soundSettingsPanel()};d.querySelector('[data-audio-music]').onclick=()=>{state.audio.music=!state.audio.music;save();if(state.audio.music){initAudio(true);startMusicScene(desiredMusicScene(),true)}else stopMusic();d.remove();soundSettingsPanel()};d.querySelector('[data-audio-sfx]').onclick=()=>{state.audio.sfx=!state.audio.sfx;save();syncAudioVolumes();d.remove();soundSettingsPanel()};const bindVol=(sel,key)=>{const r=d.querySelector(sel),o=r.nextElementSibling;r.oninput=()=>{state.audio[key]=Number(r.value)/100;o.value=r.value;syncAudioVolumes();save()}};bindVol('[data-musicvol]','musicVol');bindVol('[data-sfxvol]','sfxVol')}
'''
rep('let autoTimer=null;','let autoTimer=null;\n'+engine)

# Atmosphere lifecycle
rep('function render(){clearTimeout(autoTimer);','function render(){clearTimeout(autoTimer);syncAudioScene();updateAudioDock();')

# Feedback sounds at meaningful moments
rep("function addDisc(id,name,type='Intel'){if(state.discoveries.some(d=>d.id===id))return false;state.discoveries.unshift({id,name,type,t:Date.now()});toast('Discovery: '+name);return true}", "function addDisc(id,name,type='Intel'){if(state.discoveries.some(d=>d.id===id))return false;state.discoveries.unshift({id,name,type,t:Date.now()});sfx('discover');toast('Discovery: '+name);return true}")
rep("state.archive.upgrades[id]=l+1;if(id==='manifest')", "state.archive.upgrades[id]=l+1;sfx('upgrade');if(id==='manifest')")
rep("if(ch.combat)return encounterCombat(ch.combat,{type:'situation',sid,title:sit.title,win:ch.win||{},lose:{heat:1}});applyEffects(ch.fx||{});", "if(ch.combat)return encounterCombat(ch.combat,{type:'situation',sid,title:sit.title,win:ch.win||{},lose:{heat:1}});sfx('decision');applyEffects(ch.fx||{});")
rep("function encounterCombat(ids,context=null){resetPressure();", "function encounterCombat(ids,context=null){sfx('alert');resetPressure();")
rep("function runAutoRound(){const b=state.battle;", "function runAutoRound(){sfx('round');const b=state.battle;")
rep("if(target.hp<=0){lines.push(`<strong>${target.name} is down.</strong>`);", "if(target.hp<=0){sfx('ko');lines.push(`<strong>${target.name} is down.</strong>`);")
rep("if(!living(b.enemies).length){b.result='victory';", "if(!living(b.enemies).length){sfx('victory');b.result='victory';")
rep("if(!living(b.team).length){b.result='defeat';", "if(!living(b.team).length){sfx('defeat');b.result='defeat';")
rep("function claimEnemy(id){const t=TEMPLATES[id];", "function claimEnemy(id){const t=TEMPLATES[id];")
rep("state.claims.push(id);state.stats.claims++;", "state.claims.push(id);state.stats.claims++;sfx('claim');")
rep("state.itemClaims.push(id);state.stats.itemClaims++;", "state.itemClaims.push(id);state.stats.itemClaims++;sfx('claim');")
rep("function goHome(){clearTimeout(autoTimer);", "function goHome(){sfx('portal');clearTimeout(autoTimer);")
rep("toast('Fully stabilized');render()", "sfx('heal');toast('Fully stabilized');render()")
rep("state.battle.log=ITEMS[id].name+' used.';d.remove();render()", "state.battle.log=ITEMS[id].name+' used.';sfx('heal');d.remove();render()")
rep("document.querySelectorAll('[data-go=\"portal\"]').forEach(b=>b.onclick=()=>{state.screen='portal';render()})", "document.querySelectorAll('[data-go=\"portal\"]').forEach(b=>b.onclick=()=>{sfx('portal');state.screen='portal';render()})")

# Gear entry for audio settings
rep("<div class=\"miniBtns\"><button class=\"miniBtn\" data-upgrades>Upgrade Archive</button>", "<div class=\"miniBtns\"><button class=\"miniBtn\" data-soundsettings>Sound & Atmosphere</button><button class=\"miniBtn\" data-upgrades>Upgrade Archive</button>")
rep("d.querySelectorAll('[data-upgrades]').forEach(b=>b.onclick=()=>{d.remove();upgradePanel()});", "d.querySelectorAll('[data-soundsettings]').forEach(b=>b.onclick=()=>{d.remove();soundSettingsPanel()});d.querySelectorAll('[data-upgrades]').forEach(b=>b.onclick=()=>{d.remove();upgradePanel()});")

# First interaction can unlock a previously-enabled iPhone AudioContext; all later button taps get a tiny tactile sound.
rep("render();\nif('serviceWorker' in navigator)", "document.addEventListener('pointerdown',e=>{if(state.audio.enabled&&!audioCtx)initAudio(true);if(e.target.closest('button'))sfx('tap')},{passive:true});\nrender();\nif('serviceWorker' in navigator)")

p.write_text(text,encoding='utf-8')

sw=Path('archive-demo/sw.js')
s=sw.read_text(encoding='utf-8')
s=s.replace("const CACHE='archive-demo-v6';","const CACHE='archive-demo-v7';")
sw.write_text(s,encoding='utf-8')
print('v7 atmosphere applied',len(text))
