from pathlib import Path

INDEX=Path('archive-demo/index.html')
text=INDEX.read_text(encoding='utf-8')

def replace_line(prefix,new):
    global text
    lines=text.splitlines(); hits=[i for i,l in enumerate(lines) if l.startswith(prefix)]
    if len(hits)!=1: raise RuntimeError(f'{prefix}: {len(hits)} matches')
    lines[hits[0]]=new; text='\n'.join(lines)

replace_line('function districtAction(kind){',"function districtAction(kind){const l=CITY[state.city].locations[state.location],d=districtState();if(kind==='scout'){if(d.intel>=5){state.lastResult='<span class=\"tag\">Scouting</span>You already have a complete working read of this district. More observation will not generate free progression.';return render()}d.intel=clamp(d.intel+1,0,5);awardRes(2);state.lastResult=`<span class=\"tag\">Scouting</span>District intelligence improved to <strong>${d.intel}/5</strong>.`;save();return render()}if(kind==='confront'){const n=d.heat>=4?2:1,en=[];for(let i=0;i<n;i++){let id=rand(l.pool);if(n>1&&TEMPLATES[id].rarity==='Boss')id=rand(l.pool.filter(x=>TEMPLATES[x].rarity!=='Boss'));en.push(id)}return encounterCombat(en,{type:'district'})}if(kind==='contact'){return l.npcs.length?encounterNPC(rand(l.npcs)):(state.lastResult='<span class=\"tag\">Contact</span>No named contact is available here.',render())}if(kind==='search'){const available=(l.items||[]).filter(id=>!hasItemClaim(id));if(available.length&&chance(.55))return openItemEncounter(rand(available));if(d.intel<5){d.intel=clamp(d.intel+1,0,5);addDisc('search_'+state.city+'_'+state.location+'_'+d.intel,'Search lead: '+l.name+' '+d.intel,'Local Intel');state.lastResult=`<span class=\"tag\">Search</span>You turn up a usable lead. District intel is now <strong>${d.intel}/5</strong>.`;save();return render()}state.lastResult='<span class=\"tag\">Search</span>You have already stripped the obvious leads and unique Claim opportunities from this district. A new situation or quest is more likely to matter than repeating the search.';return render()}}")
replace_line('function openNPC(id,qid){',"function openNPC(id,qid){const n=NPCS[id],q=qid&&QUESTS[qid],qs=qid&&questState(qid),trust=relation(id),tradeKey='npcIntel_'+id,tradeCount=Number(state.flags[tradeKey]||0);let qBlock='';if(q){if(qs.status==='inactive')qBlock=`<div class=\"dialogue\"><strong>${q.name}</strong><br>${q.desc}</div><div class=\"miniBtns\"><button class=\"miniBtn active\" data-acceptq=\"${qid}\">Accept Quest</button></div>`;else if(qs.status==='active')qBlock=`<div class=\"dialogue\"><strong>Quest active: ${q.name}</strong><br>${currentObjective(qid)}</div>`;else qBlock=`<div class=\"dialogue\"><strong>${q.name} — complete</strong></div>`}const d=sheet('Character Encounter');d.querySelector('.sheet').insertAdjacentHTML('beforeend',`<div class=\"npcRow\"><div class=\"npcPortrait\">${n.icon}</div><div><h3>${n.name}</h3><p>${n.role}</p><span class=\"pill ${trust>=12?'good':trust<=-12?'danger':''}\">${standingLabel(trust)} ${trust>0?'+':''}${trust}</span></div></div><div class=\"dialogue\">${n.intro}<br><br><strong>${rand(n.lines)}</strong></div>${qBlock}<div class=\"miniBtns\"><button class=\"miniBtn\" data-npcintel ${tradeCount>=2?'disabled':''}>${tradeCount>=2?'No new intel':'Trade information'}</button><button class=\"miniBtn\" data-npcleave>Leave</button></div>`);d.querySelectorAll('[data-acceptq]').forEach(b=>b.onclick=()=>{startQuest(b.dataset.acceptq);questProgress('talk_'+id);adjustRelation(id,3);d.remove();render()});d.querySelectorAll('[data-npcintel]').forEach(b=>b.onclick=()=>{const used=Number(state.flags[tradeKey]||0);if(used>=2)return toast('No new information right now');state.flags[tradeKey]=used+1;addDisc('npc_'+id+'_'+(used+1),'Intel from '+n.name+' '+(used+1),'Character Intel');adjustRelation(id,1);save();toast(n.name+' trust +1');d.remove();openNPC(id,qid)});d.querySelectorAll('[data-npcleave]').forEach(b=>b.onclick=()=>{d.remove();state.lastResult=`<span class=\"tag\">Named Encounter</span>You met <strong>${n.name}</strong>. Relationship: ${standingLabel(relation(id))}.`;render()})}")
replace_line('function fleeBattle(){',"function fleeBattle(){const b=state.battle,avg=living(b.team).reduce((n,x)=>n+x.spd,0)/Math.max(1,living(b.team).length),enemy=living(b.enemies).reduce((n,x)=>n+x.spd,0)/Math.max(1,living(b.enemies).length);if(chance(clamp(.48+(avg-enemy)*.012,.2,.82))){b.running=false;syncJonHealthFromBattle();const committed=b.context?.type==='situation';if(committed)resolveSituationCombat(b.context,false);state.battle=null;state.screen='location';state.lastResult=committed?'<span class=\"tag\">Situation Lost</span>You escaped, but the opportunity is gone and the district absorbs the consequence.':'<span class=\"tag\">Escaped</span>Your team disengages. Damage taken before the retreat is preserved.';save();return render()}b.log='The enemy blocks your escape.';runAutoRound();render()}")

INDEX.write_text(text,encoding='utf-8')
print('v6 QoL applied',len(text))
